import Link from "next/link";
import { redirect } from "next/navigation";
import { getAdminAccessForPage } from "@/lib/access";
import { prisma } from "@/lib/prisma";
import { AdminStudioEngineerManager } from "@/components/admin-studio-engineer-manager";
export const dynamic = "force-dynamic";
const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
export default async function AdminStudioPage() {
  const admin = await getAdminAccessForPage(); if (!admin?.permissions.includes("services.manage")) redirect("/admin");
  const [orders, engineers, beatPurchases, payments, earnings, handoffs, revisions, users] = await Promise.all([
    prisma.studioServiceOrder.findMany({ include: { customer: { select: { name: true, email: true } }, engineerProfile: { select: { professionalName: true } }, payments: true }, orderBy: { updatedAt: "desc" }, take: 250 }),
    prisma.engineerProfile.findMany({ include: { listings: { orderBy: { createdAt: "asc" } }, contributorParty: { include: { claimedBy: { select: { id: true, name: true, email: true, avatar: true } } } } }, orderBy: { professionalName: "asc" } }), prisma.beatPurchase.count({ where: { hasAccess: true } }),
    prisma.studioPayment.findMany({ where: { status: "CAPTURED" }, select: { amount: true, purpose: true } }), prisma.studioEarning.aggregate({ _sum: { commissionAmount: true } }), prisma.studioReleaseHandoff.count(), prisma.studioRevision.count(),
    prisma.user.findMany({ where: { status: "ACTIVE", OR: [{ claimedContributorParty: null }, { claimedContributorParty: { is: { engineerProfile: null } } }] }, select: { id: true, name: true, email: true, avatar: true }, orderBy: [{ name: "asc" }, { email: "asc" }], take: 1000 }),
  ]);
  const total=orders.length, completed=orders.filter(o=>o.status==="COMPLETED"), cancelled=orders.filter(o=>o.status==="CANCELLED").length, refunded=orders.filter(o=>o.status==="REFUNDED").length, beatLinked=orders.filter(o=>o.sourceBeatPurchaseId).length;
  const gmv=payments.reduce((sum,row)=>sum+Number(row.amount),0), paidRevisionRevenue=payments.filter(row=>row.purpose==="ADDITIONAL_REVISION").reduce((sum,row)=>sum+Number(row.amount),0);
  const turnaround=completed.map(o=>o.startedAt&&o.completedAt?(o.completedAt.getTime()-o.startedAt.getTime())/86400000:null).filter((v):v is number=>v!==null);
  const percent=(value:number,denominator=total)=>denominator?`${((value/denominator)*100).toFixed(1)}%`:"—";
  const metrics=[["Beat → Studio",percent(beatLinked,beatPurchases),`${beatLinked} linked orders`],["Studio GMV",money(gmv),"Captured payments"],["HYMN revenue",money(Number(earnings._sum.commissionAmount??0)),"Released commission"],["Average order",total?money(gmv/total):"—","Captured GMV / orders"],["Revisions / order",total?(revisions/total).toFixed(2):"—",`${revisions} requests`],["Paid revisions",money(paidRevisionRevenue),"Verified payments"],["Completion",percent(completed.length),`${completed.length} completed`],["Cancellation",percent(cancelled),`${cancelled} cancelled`],["Refund",percent(refunded),`${refunded} refunded`],["Avg turnaround",turnaround.length?`${(turnaround.reduce((a,b)=>a+b,0)/turnaround.length).toFixed(1)} days`:"—","Start to completion"],["Studio → Distribution",percent(handoffs,completed.length),`${handoffs} handoffs`],["Engineers",String(engineers.length),"Canonical profiles"]];
  const stringList = (value: unknown, key: string) => value && typeof value === "object" && !Array.isArray(value) && Array.isArray((value as Record<string, unknown>)[key]) ? ((value as Record<string, unknown>)[key] as unknown[]).filter((item): item is string => typeof item === "string") : [];
  const portfolioData = (value: unknown) => {
    const record = value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
    const socials = record.socials && typeof record.socials === "object" && !Array.isArray(record.socials) ? record.socials as Record<string, unknown> : {};
    const works = Array.isArray(value) ? value : Array.isArray(record.works) ? record.works : [];
    return { socialLinks: { instagram: typeof socials.instagram === "string" ? socials.instagram : "", youtube: typeof socials.youtube === "string" ? socials.youtube : "" }, portfolioItems: works.flatMap(item => { if (!item || typeof item !== "object") return []; const work = item as Record<string, unknown>, url = typeof work.url === "string" ? work.url : typeof work.afterUrl === "string" ? work.afterUrl : null; return url ? [{ title: typeof work.title === "string" ? work.title : "Featured work", url }] : []; }) };
  };
  const roster = engineers.flatMap(engineer => {
    const listing = engineer.listings[0], user = engineer.contributorParty.claimedBy;
    if (!listing || !user) return [];
    return [{ id: engineer.id, userId: user.id, userName: user.name, userEmail: user.email, userAvatar: user.avatar ?? "", professionalName: engineer.professionalName, slug: engineer.slug, profilePhotoUrl: engineer.profilePhotoUrl ?? user.avatar ?? "", bio: engineer.bio, specialties: engineer.specialties, genres: engineer.genres, ...portfolioData(engineer.portfolio), availability: engineer.availability, maxActiveOrders: engineer.maxActiveOrders, verificationState: engineer.verificationState, sellerState: engineer.sellerState, payoutState: engineer.payoutState, listing: { title: listing.title, description: listing.description, standardPrice: Number(listing.standardPrice), beatCustomerPrice: listing.beatCustomerPrice === null ? null : Number(listing.beatCustomerPrice), includedRevisions: listing.includedRevisions, additionalRevisionPrice: Number(listing.additionalRevisionPrice), turnaroundDays: listing.turnaroundDays, sourceRequirements: stringList(listing.sourceRequirements, "required"), deliverables: stringList(listing.deliverables, "files"), instantAccept: listing.instantAccept, active: listing.active, paused: listing.paused } }];
  });
  return <main className="shell py-8"><header><p className="hymn-kicker">Operations</p><h1 className="mt-2 text-3xl font-semibold">Studio Services</h1><p className="mt-2 text-[var(--text-muted)]">Appoint engineers, manage their public services, and monitor Studio commerce from one operations view.</p></header><AdminStudioEngineerManager users={users} engineers={roster}/><section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,detail])=><div className="metric-card" key={label}><p className="text-xs uppercase tracking-[.14em] text-[var(--text-soft)]">{label}</p><strong className="mt-3 block text-2xl">{value}</strong><small className="mt-1 block text-[var(--text-muted)]">{detail}</small></div>)}</section><section className="mt-7 overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--card)]"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b border-[var(--border)] text-[var(--text-soft)]"><tr><th className="p-4">Project</th><th>Customer</th><th>Engineer</th><th>Status</th><th>Payment</th><th>Updated</th></tr></thead><tbody>{orders.map(order=><tr key={order.id} className="border-b border-[var(--border)]"><td className="p-4"><Link className="font-semibold underline" href={`/studio/orders/${order.publicId}`}>{order.projectTitle}</Link><small className="mt-1 block text-[var(--text-soft)]">#{order.publicId.slice(0,8)} · {order.sourceBeatPurchaseId?"HYMN Beat":"External production"}</small></td><td>{order.customer.name}<br/><small>{order.customer.email}</small></td><td>{order.engineerProfile.professionalName}</td><td>{order.status.replaceAll("_"," ")}</td><td>{order.paymentStatus}</td><td>{order.updatedAt.toLocaleString("en-IN")}</td></tr>)}</tbody></table></section></main>;
}
