import type { Metadata } from "next";
import Link from "next/link";
import { growthTouch } from "@/lib/growth-domain";
export const metadata: Metadata = {
  title: "Release Your First Track Free | HYMN Music",
  description: "Start with one Single. HYMN covers the ₹99 base distribution fee for eligible new artists. Review, release tracking and support from one account.",
  alternates: { canonical: "/first-release-free" },
  openGraph: { title: "Release Your First Track Free", description: "Get started with music distribution through HYMN.", url: "/first-release-free", type: "website" },
  twitter: { card: "summary", title: "Release Your First Track Free | HYMN" }
};
export default async function FreeReleaseLanding({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const query = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) if (typeof value === "string") query.set(key, value);
  const touch = growthTouch(`/?${query}`); const kept = new URLSearchParams();
  for (const [key, value] of Object.entries(touch)) if (key.startsWith("utm_") || key === "ref") kept.set(key, value);
  const href = `/first-release?${kept}`;
  return <main className="shell pb-28 pt-12 sm:py-20"><section className="max-w-3xl"><p className="eyebrow">Music distribution for independent artists</p><h1 className="mt-5 text-4xl font-semibold tracking-tight sm:text-6xl">Release Your First Track Free.</h1><p className="mt-6 text-lg leading-8">Get your music distributed through HYMN and experience the release process before committing to a plan.</p><p className="mt-4 text-sm">One Single per eligible account. The ₹99 base distribution fee is covered. Optional add-ons are shown before submission.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary" href={href}>Release My First Track</Link><Link className="btn-outline" href="/login">Already have HYMN? Log in</Link></div></section><p className="my-12 border-y py-5 text-sm">Spotify · Apple Music · YouTube Music · Amazon Music</p><section><h2 className="text-2xl font-semibold">How it works</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Create your HYMN account", "Upload your release and metadata", "HYMN reviews your submission", "Track progress from your dashboard"].map((step, index) => <article className="surface-card p-5" key={step}><p className="text-sm">0{index + 1}</p><h3 className="mt-4 font-semibold">{step}</h3></article>)}</div></section><section className="my-12 grid gap-5 sm:grid-cols-3">{[["Human review", "Metadata, artwork and audio checks before processing."], ["Artist dashboard", "Manage drafts and follow release progress from your account."], ["Release support", "Contact HYMN when you need help with your submission."]].map(([title, body]) => <article key={title}><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3">{body}</p></article>)}</section><section className="max-w-3xl"><h2 className="mb-6 text-2xl font-semibold">Before you start</h2>{[["Is my first release really free?", "For an eligible account, HYMN covers the ₹99 base fee for one new Single. Optional add-ons remain payable. Eligibility is confirmed before submission."], ["What happens after my first release?", "You can return for another release or compare the recurring plans on the distribution page."], ["Do I need a subscription?", "A recurring subscription is not required for the first-release offer."], ["When should I submit?", "Submit before your intended release date with complete metadata and assets. Review and store processing affect timing; contact HYMN for help planning your release."]].map(([question, answer]) => <details key={question} className="border-b py-4"><summary className="cursor-pointer font-semibold">{question}</summary><p className="mt-3 leading-7">{answer}</p></details>)}<Link className="btn-outline mt-6" href="/distribution">View distribution plans</Link></section><div className="fixed inset-x-0 bottom-0 z-30 border-t bg-[var(--bg)] p-3 sm:hidden"><Link className="btn-primary block text-center" href={href}>Release My First Track</Link></div></main>;
}
