import { z } from "zod";
import { requireUser } from "@/lib/access";
import { apiFailure, apiRequestId, apiSuccess } from "@/lib/api-response";
import { createManagedServiceRequest } from "@/lib/managed-services";
import { prisma } from "@/lib/prisma";
import { consumeRateLimit } from "@/lib/rate-limit";

const schema = z.object({ releaseId: z.number().int().positive(), trackId: z.number().int().positive().optional(), serviceType: z.enum(["CRBT_CALLER_TUNE", "YOUTUBE_OAC", "YOUTUBE_CONTENT_ID"]), provider: z.string().trim().max(100).optional(), answers: z.record(z.string(), z.unknown()), declarations: z.record(z.string(), z.unknown()).optional(), publicLinks: z.array(z.string().url()).max(20).optional(), documentAssetIds: z.array(z.number().int().positive()).max(20).optional(), requestKey: z.string().trim().min(8).max(200) });
export async function GET(request: Request) { const requestId = apiRequestId(request); const user = await requireUser(); if ("error" in user) return apiFailure(requestId, "UNAUTHENTICATED", "Authentication required.", 401); const query = new URL(request.url).searchParams; const limit = Math.max(1, Math.min(Number(query.get("limit") || 25), 100)); const cursor = Number(query.get("cursor") || 0) || undefined; const rows = await prisma.managedServiceRequest.findMany({ where: { userId: user.user.id, ...(cursor ? { id: { lt: cursor } } : {}) }, orderBy: { id: "desc" }, take: limit + 1, include: { release: { select: { title: true, artistName: true } }, documents: { include: { asset: { select: { id: true, safeFilename: true, mimeType: true, byteSize: true } } } }, providerStatuses: true } }); const hasMore = rows.length > limit; const requests = rows.slice(0, limit); return apiSuccess(requestId, { requests, processing: "manual_by_hymn", page: { nextCursor: hasMore ? requests.at(-1)?.id ?? null : null, limit } }); }
export async function POST(request: Request) { const requestId = apiRequestId(request); const user = await requireUser(); if ("error" in user) return apiFailure(requestId, "UNAUTHENTICATED", "Authentication required.", 401); const rate = await consumeRateLimit({ scope: "managed-service-submit", identity: String(user.user.id), limit: 10, windowSeconds: 3600 }); if (!rate.allowed) return apiFailure(requestId, "RATE_LIMITED", `Too many requests. Retry in ${rate.retryAfterSeconds} seconds.`, 429); try { const body = schema.parse(await request.json()); const result = await createManagedServiceRequest({ userId: user.user.id, ...body }); return apiSuccess(requestId, { request: result, message: "HYMN will manually review and submit eligible requests. Availability and turnaround depend on partner approval; submission does not guarantee activation." }, { status: 201 }); } catch (error) { if (error instanceof z.ZodError) { const fields = Object.fromEntries(Object.entries(error.flatten().fieldErrors).filter((entry): entry is [string, string[]] => Array.isArray(entry[1]))); return apiFailure(requestId, "VALIDATION_ERROR", "Review the managed-service details and try again.", 400, fields); } return apiFailure(requestId, "REQUEST_FAILED", error instanceof Error ? error.message : "Request failed.", 400); } }
// vercel trigger 9
