import { createHash } from "crypto";
import ExcelJS from "exceljs";
import { put } from "@vercel/blob";
import { prisma } from "@/lib/prisma";
import { logAuditEvent } from "@/lib/audit-log";

type Request = { type: "monthly" | "quarterly" | "user_statement" | "master"; month?: number; quarter?: number; year: number; userId?: number; actorId?: number | null; persist?: boolean };
const n = (value: any) => typeof value?.toNumber === "function" ? value.toNumber() : Number(value || 0);
function range(input: Request) { if (input.type === "master") return {}; if (input.type === "monthly") return { gte: new Date(Date.UTC(input.year,input.month!-1,1)), lte: new Date(Date.UTC(input.year,input.month!,0,23,59,59,999)) }; return { gte: new Date(Date.UTC(input.year,(input.quarter!-1)*3,1)), lte: new Date(Date.UTC(input.year,input.quarter!*3,0,23,59,59,999)) }; }
function fileName(input: Request) { if (input.type === "monthly") return `hymn-payout-monthly-${new Date(2000,input.month!-1,1).toLocaleString("en",{month:"long"}).toLowerCase()}-${input.year}.xlsx`; if (input.type === "user_statement") return `hymn-payout-statement-${input.userId}-Q${input.quarter}-${input.year}.xlsx`; if (input.type === "quarterly") return `hymn-payout-quarterly-Q${input.quarter}-${input.year}.xlsx`; return `hymn-payout-master-ledger-${input.year}.xlsx`; }
function addSheet(workbook: ExcelJS.Workbook, name: string, rows: any[]) { const sheet=workbook.addWorksheet(name); const safe=rows.map(row=>Object.fromEntries(Object.entries(row).filter(([key])=>!["bankAccountNumber","upiId","upiIdEncrypted","bankAccountEncrypted","ifscEncrypted","taxInfoEncrypted"].includes(key)).map(([key,value])=>[key,typeof value==="object"&&value&&!(value instanceof Date)?JSON.stringify(value):value]))); if(safe[0]){sheet.columns=Object.keys(safe[0]).map(key=>({header:key,key,width:Math.min(42,Math.max(14,key.length+2))}));safe.forEach(row=>sheet.addRow(row));sheet.getRow(1).font={bold:true};sheet.views=[{state:"frozen",ySplit:1}];} return sheet; }
export async function generatePayoutWorkbook(input: Request) {
  if(!Number.isInteger(input.year)||input.year<2020||input.year>new Date().getUTCFullYear()+1)throw new Error("Invalid report year.");
  if(input.type==="monthly"&&(!Number.isInteger(input.month)||input.month!<1||input.month!>12))throw new Error("Invalid report month.");
  if(["quarterly","user_statement"].includes(input.type)&&(!Number.isInteger(input.quarter)||input.quarter!<1||input.quarter!>4))throw new Error("Invalid report quarter.");
  const dates=range(input); const royaltyWhere=Object.keys(dates).length?{statementMonth:dates}:{}; const userSplit=input.userId?{recipientUserId:input.userId}:{}; const userWallet=input.userId?{userId:input.userId}:{};
  const [royalties,splits,recipients,earnings,wallet,payouts,carry,unmatched,audits]=await Promise.all([(prisma as any).royaltyLineItem.findMany({where:royaltyWhere}),(prisma as any).splitRecord.findMany({where:input.userId?{OR:[{ownerUserId:input.userId},{recipients:{some:{recipientUserId:input.userId}}}]}:{}}),(prisma as any).splitRecipient.findMany({where:input.userId?{recipientUserId:input.userId}:{}}),(prisma as any).splitEarningLineItem.findMany({where:{...userSplit,...(Object.keys(dates).length?{royaltyLineItem:{statementMonth:dates}}:{})}}),(prisma as any).walletTransaction.findMany({where:{...userWallet,...(Object.keys(dates).length?{createdAt:dates}:{})}}),(prisma as any).payoutRequest.findMany({where:{...userWallet,...(Object.keys(dates).length?{requestedAt:dates}:{})}}),(prisma as any).quarterCarryForward.findMany({where:input.userId?{userId:input.userId}:{}}),(prisma as any).unmatchedRoyaltyRow.findMany({where:Object.keys(dates).length?{statementMonth:dates}:{}}),(prisma as any).auditLog.findMany({where:{OR:[{entity:{contains:"payout"}},{entity:{contains:"split"}},{entity:{contains:"royalty"}},{entity:{contains:"quarter"}}]}})]);
  const producerSales=await (prisma as any).beatSale.findMany({where:{...(input.userId?{producerUserId:input.userId}:{}),...(Object.keys(dates).length?{createdAt:dates}:{})},include:{beat:{select:{title:true}},producer:{select:{name:true}},buyer:{select:{name:true}}},orderBy:{createdAt:"desc"}});
  const producerLedger=wallet.filter((entry:any)=>entry.referenceType==="beat_sale"||String(entry.type).startsWith("producer_"));
  const producerPayouts=payouts.filter((entry:any)=>["producer_beat_sales","mixed"].includes(entry.sourceType));
  const totalRows=royalties.length+splits.length+recipients.length+earnings.length+wallet.length+payouts.length+carry.length+unmatched.length+audits.length;
  if(totalRows>100000)throw new Error("This report exceeds 100,000 rows. Generate a narrower monthly or quarterly report.");
  const workbook=new ExcelJS.Workbook();workbook.creator="HYMN";workbook.created=new Date(); const summary=workbook.addWorksheet("Summary"); const gross=royalties.reduce((s:any,r:any)=>s+n(r.grossRevenue),0),commission=royalties.reduce((s:any,r:any)=>s+n(r.hymnServiceFee),0),pool=royalties.reduce((s:any,r:any)=>s+n(r.netRevenue),0),splitTotal=earnings.reduce((s:any,r:any)=>s+n(r.netShareAmount),0),held=earnings.filter((r:any)=>["held","pending_payout_details"].includes(r.status)).reduce((s:any,r:any)=>s+n(r.netShareAmount),0),requested=payouts.reduce((s:any,r:any)=>s+n(r.amount),0),fee=payouts.reduce((s:any,r:any)=>s+n(r.serviceFee),0),paid=payouts.filter((r:any)=>r.status==="PAID").reduce((s:any,r:any)=>s+n(r.netAmount),0),carryTotal=carry.reduce((s:any,r:any)=>s+n(r.amount),0);
  [["Report Type",input.type],["Month / Quarter",input.month?input.month:input.quarter?`Q${input.quarter}`:"All"],["Year",input.year],["Generated At",new Date().toISOString()],["Generated By",input.actorId?`Admin ${input.actorId}`:input.userId?`User ${input.userId}`:"System"],["Period Start Date",(dates as any).gte?.toISOString()||"All"],["Period End Date",(dates as any).lte?.toISOString()||"All"],["Total Gross Revenue",gross],["Total HYMN Commission",commission],["Total Artist Pool",pool],["Total Split Earnings",splitTotal],["Total Held Balance",held],["Total Requested Payout",requested],["Total Service Fee",fee],["Total Net Payable",requested-fee],["Total Paid",paid],["Total Carry Forward",carryTotal],["Total Unmatched Rows",unmatched.length]].forEach(row=>summary.addRow(row)); summary.getColumn(1).font={bold:true};summary.getColumn(1).width=30;summary.getColumn(2).width=34;
  addSheet(workbook,"Royalty Line Items",royalties);addSheet(workbook,"Split Records",splits);addSheet(workbook,"Split Recipients",recipients);addSheet(workbook,"Split Earnings",earnings);addSheet(workbook,"Producer Sales",producerSales.map((sale:any)=>({beatSaleId:sale.id,beatId:sale.beatId,beatTitle:sale.beat?.title,producerUserId:sale.producerUserId,producerDisplayName:sale.producer?.name,buyerUserId:sale.buyerUserId,buyerName:sale.buyer?.name,orderId:sale.orderId,paymentId:sale.paymentId,grossAmount:n(sale.grossAmount),hymnCommission30:n(sale.hymnCommissionAmount),producerEarning70:n(sale.producerEarningAmount),currency:sale.currency,licenseType:sale.licenseType,saleStatus:sale.status,earningSource:"beat_sale",createdAt:sale.createdAt})));addSheet(workbook,"Producer Ledger",producerLedger);addSheet(workbook,"Producer Payouts",producerPayouts);addSheet(workbook,"Wallet Ledger",wallet);addSheet(workbook,"Payout Requests",payouts);addSheet(workbook,"Paid Payouts",payouts.filter((r:any)=>r.status==="PAID"));addSheet(workbook,"Carry Forward",carry);addSheet(workbook,"Unmatched UPC ISRC",unmatched);addSheet(workbook,"Audit Logs",audits);
  const buffer=Buffer.from(await workbook.xlsx.writeBuffer());const checksum=createHash("sha256").update(buffer).digest("hex"); const name=fileName(input);
  let storagePath:string|null=null;
  if(input.persist!==false&&process.env.BLOB_READ_WRITE_TOKEN){const blob=await put(`payout-reports/${checksum}-${name}`,buffer,{access:"private",addRandomSuffix:false,contentType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});storagePath=blob.url;}
  else if(input.persist!==false&&process.env.NODE_ENV==="production")throw new Error("Private report storage is not configured.");
  const report=input.persist===false?{id:0,type:input.type,userId:input.userId??null,month:input.month??null,quarter:input.quarter??null,year:input.year,fileName:name,status:"generated",checksum,storagePath,generatedAt:new Date()}:await (prisma as any).payoutReport.create({data:{type:input.type,userId:input.userId??null,month:input.month??null,quarter:input.quarter??null,year:input.year,fileName:name,storagePath,generatedByAdminId:input.actorId??null,status:"generated",checksum}});
  if(input.persist!==false)await logAuditEvent({actorType:input.actorId?"admin":input.userId?"user":"system",actorId:input.actorId??input.userId??null,entityType:"payout_report",entityId:report.id,action:`${input.type}.report_generated`,newValue:{fileName:name,checksum}});
  return {...report,buffer};
}

export async function recordReportFailure(input: Omit<Request, "persist">, error: unknown) {
  const name=fileName(input);const message=error instanceof Error?error.message:"Unknown report generation error";
  const report=await (prisma as any).payoutReport.create({data:{type:input.type,userId:input.userId??null,month:input.month??null,quarter:input.quarter??null,year:input.year,fileName:name,generatedByAdminId:input.actorId??null,status:"failed"}});
  await logAuditEvent({actorType:input.actorId?"admin":input.userId?"user":"system",actorId:input.actorId??input.userId??null,entityType:"payout_report",entityId:report.id,action:"report.generation_failed",metadata:{message,fileName:name}});
  return report;
}
// vercel trigger 7
