"use client";

import { FormEvent, useState } from "react";

export function AdminContributorManager({ initialContributors }: { initialContributors: any[] }) {
  const [contributors, setContributors] = useState(initialContributors);
  const [query, setQuery] = useState("");
  const [message, setMessage] = useState("");
  async function search(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/admin/contributors?q=${encodeURIComponent(query)}`, { cache: "no-store" }); const body = await response.json(); if (response.ok) setContributors(body.contributors ?? []); else setMessage(body.error || "Search failed."); }
  async function merge(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const response = await fetch("/api/admin/contributors/merge", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourcePartyId: Number(data.get("sourcePartyId")), targetPartyId: Number(data.get("targetPartyId")), evidence: { reason: String(data.get("reason") ?? ""), reviewedAt: new Date().toISOString() } }) }); const body = await response.json(); setMessage(response.ok ? `Merged ${body.sourcePublicId} into ${body.targetPublicId}. Historical snapshots were retained.` : body.error || "Merge failed."); }
  return <div className="grid gap-6"><form onSubmit={search} className="flex gap-3"><input className="field flex-1" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search professional name or HYMN contributor ID" /><button className="btn-primary">Search</button></form><div className="overflow-x-auto rounded-2xl border" style={{ borderColor: "var(--border)" }}><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Identity</th><th className="p-3">State</th><th className="p-3">Relationships</th></tr></thead><tbody>{contributors.map((party) => <tr key={party.id} className="border-t" style={{ borderColor: "var(--border)" }}><td className="p-3"><strong>{party.professionalName}</strong><br /><span className="text-xs" style={{ color: "var(--text-muted)" }}>{party.publicId}</span></td><td className="p-3">{party.identityState}{party.mergedInto ? ` → ${party.mergedInto.publicId}` : ""}</td><td className="p-3">{party._count?.contributions ?? 0} credits · {party._count?.beats ?? 0} beats · {party._count?.splitRecipients ?? 0} splits</td></tr>)}</tbody></table></div><form onSubmit={merge} className="surface-card grid gap-4 p-5 sm:grid-cols-2"><div className="sm:col-span-2"><h2 className="text-xl font-semibold">Evidence-backed identity merge</h2><p className="mt-1 text-sm" style={{ color: "var(--text-muted)" }}>Recent admin authentication is required. Claimed-account and public-profile conflicts are rejected.</p></div><input className="field" name="sourcePartyId" type="number" min="1" required placeholder="Source internal ID" /><input className="field" name="targetPartyId" type="number" min="1" required placeholder="Target internal ID" /><textarea className="field sm:col-span-2" name="reason" required minLength={10} placeholder="Verified evidence and reason" /><button className="btn-primary sm:col-span-2">Merge identities</button></form>{message ? <p aria-live="polite" className="text-sm">{message}</p> : null}</div>;
}
