"use client";

import { FormEvent, useEffect, useState } from "react";
import type { User } from "@/lib/types";

type Role = { key: string; name: string; description?: string | null; permissions: string[]; memberCount: number };
type Membership = { id: number; userId: number; user: { id: number; name: string; email: string }; role: string; roleName: string; active: boolean; permissions: string[]; updatedAt: string };
const group = (key: string) => key.split(".")[0].replace("kyc", "identity");

export function AdminTeamAccessManager({ users, canManage }: { users: User[]; canManage: boolean }) {
  const [roles, setRoles] = useState<Role[]>([]);
  const [memberships, setMemberships] = useState<Membership[]>([]);
  const [legacyAdmins, setLegacyAdmins] = useState<Array<{ id: number; name: string; email: string }>>([]);
  const [pending, setPending] = useState(false);
  const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/admin/memberships", { cache: "no-store" }); if (!response.ok) return; const data = await response.json(); setRoles(data.roles || []); setMemberships(data.memberships || []); setLegacyAdmins(data.legacyAdmins || []); }
  useEffect(() => { if (canManage) load(); }, [canManage]);
  async function assign(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const userId = Number(form.get("userId")); const role = String(form.get("role")); const reason = String(form.get("reason")); setPending(true); setMessage(""); const response = await fetch(`/api/admin/memberships/${userId}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role, active: true, reason }) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? "Limited admin role assigned." : data.error || "Could not update team access."); setPending(false); if (response.ok) load(); }
  async function toggle(item: Membership, active: boolean) { const reason = window.prompt(active ? "Reason for restoring this staff access:" : "Reason for revoking this staff access:"); if (!reason || reason.trim().length < 5) return; setPending(true); const response = await fetch(`/api/admin/memberships/${item.userId}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role: item.role, active, reason }) }); setPending(false); if (response.ok) load(); }
  if (!canManage) return <section className="surface-card p-6"><h2 className="text-xl font-semibold">Team access</h2><p className="mt-2 text-sm" style={{ color: "var(--text-muted)" }}>Only a super admin or staff member with System Manage permission can assign or revoke admin roles.</p></section>;
  return <div className="grid gap-6">
    <section className="surface-card p-5 sm:p-6"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em]" style={{ color: "var(--accent)" }}>Power map</p><h2 className="mt-2 text-2xl font-semibold">Admin roles and boundaries</h2><p className="mt-2 text-sm" style={{ color: "var(--text-muted)" }}>Choose the smallest role that matches the person’s job. Super admin includes every platform permission.</p></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{roles.map((role) => <article key={role.key} className="rounded-2xl border p-4" style={{ borderColor: role.key === "super_admin" ? "var(--accent)" : "var(--border)", background: "var(--bg-soft)" }}><div className="flex items-start justify-between gap-2"><h3 className="font-semibold">{role.name}</h3><span className="status-pill">{role.memberCount}</span></div><p className="mt-2 min-h-10 text-xs leading-5" style={{ color: "var(--text-muted)" }}>{role.description || (role.key === "super_admin" ? "Unrestricted platform control. Assign very rarely." : "Limited operational access.")}</p><div className="mt-3 flex flex-wrap gap-1.5">{[...new Set(role.permissions.map(group))].map((area) => <span key={area} className="rounded-full border px-2 py-1 text-[10px] capitalize" style={{ borderColor: "var(--border)" }}>{area}</span>)}</div><details className="mt-3"><summary className="cursor-pointer text-xs font-semibold">{role.permissions.length} exact permissions</summary><ul className="mt-2 grid gap-1 text-[11px]" style={{ color: "var(--text-soft)" }}>{role.permissions.map((permission) => <li key={permission}>• {permission}</li>)}</ul></details></article>)}</div></section>
    <section className="grid gap-5 xl:grid-cols-[0.8fr,1.2fr]"><form onSubmit={assign} className="surface-card grid content-start gap-4 p-5"><div><h2 className="text-xl font-semibold">Give limited admin access</h2><p className="mt-2 text-sm" style={{ color: "var(--text-muted)" }}>The selected user becomes an admin but receives only the chosen role’s permissions.</p></div><label className="grid gap-2 text-sm">Person<select name="userId" required className="field"><option value="">Choose a user</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select></label><label className="grid gap-2 text-sm">Staff role<select name="role" required className="field"><option value="">Choose the minimum role</option>{roles.map((role) => <option key={role.key} value={role.key}>{role.name} · {role.permissions.length} permissions</option>)}</select></label><label className="grid gap-2 text-sm">Reason<input name="reason" required minLength={5} className="field" placeholder="Job responsibility and approval reference" /></label><button disabled={pending} className="btn-primary pressable">{pending ? "Saving…" : "Assign limited access"}</button>{message ? <p className="text-sm">{message}</p> : null}</form><div className="surface-card p-5"><h2 className="text-xl font-semibold">Current staff access</h2>{legacyAdmins.length ? <div className="mt-4 rounded-2xl border p-4" style={{ borderColor: "color-mix(in srgb, #eab308 55%, var(--border))", background: "color-mix(in srgb, #eab308 9%, var(--card))" }}><p className="font-semibold">⚠ {legacyAdmins.length} legacy full-access admin{legacyAdmins.length === 1 ? "" : "s"}</p><p className="mt-1 text-xs" style={{ color: "var(--text-muted)" }}>These admin accounts have no explicit membership and currently inherit full access. Assign each one a role below to make access clear and limited.</p><p className="mt-2 text-xs">{legacyAdmins.map((user) => `${user.name} (${user.email})`).join(", ")}</p></div> : null}<div className="mt-4 grid gap-3">{memberships.map((item) => <article key={item.id} className="rounded-2xl border p-4" style={{ borderColor: "var(--border)" }}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{item.user.name}</p><p className="mt-1 text-xs" style={{ color: "var(--text-muted)" }}>{item.user.email}</p><p className="mt-2 text-sm capitalize">{item.roleName} · {item.permissions.length} permissions</p></div><button type="button" disabled={pending} onClick={() => toggle(item, !item.active)} className={item.active ? "btn-outline pressable" : "btn-primary pressable"}>{item.active ? "Revoke access" : "Restore access"}</button></div></article>)}</div></div></section>
  </div>;
}
