"use client";
import { useEffect, useState } from "react";

type Campaign = { id: number; subject: string; status: string; recipientCount: number; sentCount: number; failedCount: number; createdAt: string };
export function AdminNewsletter() {
  const [data, setData] = useState<{ total: number; unsubscribed: number; campaigns: Campaign[]; configured: boolean } | null>(null);
  const [subject, setSubject] = useState(""); const [message, setMessage] = useState(""); const [campaignId, setCampaignId] = useState<number | null>(null); const [feedback, setFeedback] = useState<string | null>(null); const [sending, setSending] = useState(false);
  const load = () => fetch("/api/admin/newsletter").then(async r => { const body = await r.json(); if (!r.ok) throw new Error(body.error || "Could not load newsletter."); setData(body); }).catch(e => setFeedback(e.message));
  useEffect(() => { load(); }, []);
  async function copyList() { const response = await fetch("/api/admin/newsletter?format=text"); const text = await response.text(); await navigator.clipboard.writeText(text); setFeedback(`${data?.total || 0} active emails copied.`); }
  async function send() { setSending(true); setFeedback(null); try { const response = await fetch("/api/admin/newsletter", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject, message, ...(campaignId ? { campaignId } : {}) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Could not send this batch."); setCampaignId(body.campaign.id); setFeedback(body.complete ? `Campaign complete: ${body.campaign.sentCount} sent, ${body.campaign.failedCount} failed.` : `${body.processed} sent. ${body.remaining} recipients remain; select Send next batch.`); load(); } catch (error) { setFeedback(error instanceof Error ? error.message : "Could not send this batch."); } finally { setSending(false); } }
  return <section className="surface-card p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--text-soft)]">Newsletter</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">Subscriber mailing</h1><p className="mt-2 text-sm text-[var(--text-muted)]">Every campaign includes a personal unsubscribe link. Send in controlled batches of 50.</p></div><span className="status-pill">{data?.configured ? "Resend ready" : "Resend unavailable"}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Subscribed", data?.total ?? "—"], ["Unsubscribed", data?.unsubscribed ?? "—"], ["Campaigns", data?.campaigns.length ?? "—"]].map(([label, value]) => <div key={label as string} className="rounded-xl border p-4" style={{ borderColor: "var(--border)", background: "var(--bg-soft)" }}><p className="text-xs text-[var(--text-soft)]">{label}</p><strong className="mt-1 block text-2xl">{value}</strong></div>)}</div><div className="mt-6 flex flex-wrap gap-2"><button onClick={copyList} className="btn-outline">Copy active email list</button><a href="/api/admin/newsletter?format=csv" className="btn-outline">Download CSV</a></div><div className="mt-7 grid gap-4 border-t pt-6" style={{ borderColor: "var(--border)" }}><label className="grid gap-2 text-sm font-semibold">Subject<input value={subject} onChange={e => { setSubject(e.target.value); setCampaignId(null); }} className="field" maxLength={180} placeholder="HYMN Music update" /></label><label className="grid gap-2 text-sm font-semibold">Message<textarea value={message} onChange={e => { setMessage(e.target.value); setCampaignId(null); }} className="field min-h-40" maxLength={20000} placeholder="Write the newsletter message. Paragraphs are preserved." /></label><div className="flex flex-wrap items-center gap-3"><button disabled={sending || !data?.configured} onClick={send} className="btn-primary">{sending ? "Sending…" : campaignId ? "Send next batch" : "Start campaign"}</button>{campaignId ? <span className="text-sm text-[var(--text-muted)]">Campaign #{campaignId}</span> : null}</div>{feedback ? <p className="text-sm" aria-live="polite">{feedback}</p> : null}</div><div className="mt-8 border-t pt-6" style={{ borderColor: "var(--border)" }}><h2 className="font-semibold">Recent campaigns</h2><div className="mt-3 grid gap-2">{data?.campaigns.map(c => <div key={c.id} className="summary-card"><span><strong>{c.subject}</strong><small className="block">{new Date(c.createdAt).toLocaleString()}</small></span><span>{c.status} · {c.sentCount}/{c.recipientCount} sent{c.failedCount ? ` · ${c.failedCount} failed` : ""}</span></div>) || null}</div></div></section>;
}
