"use client";

import { CheckCircle2, Search, Star, XCircle } from "lucide-react";
import { useCallback, useEffect, useState, useTransition } from "react";

type Review = { id: number; purchaseType: string; purchaseLabel: string; rating: number; body: string | null; status: string; featured: boolean; featuredOrder: number; createdAt: string; user: { name: string; email: string; avatar: string | null }; moderatedBy: { name: string } | null };
type ReviewResponse = { reviews: Review[]; page: { current: number; pages: number; total: number }; metrics: { pending: number; featured: number } };

export function AdminReviewManager() {
  const [data, setData] = useState<ReviewResponse | null>(null);
  const [status, setStatus] = useState("all");
  const [query, setQuery] = useState("");
  const [page, setPage] = useState(1);
  const [feedback, setFeedback] = useState("");
  const [isPending, startTransition] = useTransition();
  const load = useCallback(async () => { const params = new URLSearchParams({ status, page: String(page) }); if (query.trim()) params.set("q", query.trim()); const response = await fetch(`/api/admin/reviews?${params}`, { cache: "no-store" }); const payload = await response.json(); if (response.ok) setData(payload); else setFeedback(payload.error || "Reviews could not be loaded."); }, [page, query, status]);
  useEffect(() => { void load(); }, [load]);
  function update(id: number, patch: Record<string, unknown>) { startTransition(async () => { const response = await fetch(`/api/admin/reviews/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }); const payload = await response.json(); setFeedback(response.ok ? "Review moderation saved." : payload.error || "Review could not be updated."); if (response.ok) await load(); }); }
  return <div className="grid gap-5">
    <section className="grid gap-3 sm:grid-cols-3"><div className="surface-card p-5"><p className="text-sm text-[var(--text-muted)]">All matching</p><p className="mt-2 text-3xl font-semibold">{data?.page.total ?? "—"}</p></div><div className="surface-card p-5"><p className="text-sm text-[var(--text-muted)]">Awaiting review</p><p className="mt-2 text-3xl font-semibold">{data?.metrics.pending ?? "—"}</p></div><div className="surface-card p-5"><p className="text-sm text-[var(--text-muted)]">Homepage featured</p><p className="mt-2 text-3xl font-semibold">{data?.metrics.featured ?? "—"}</p></div></section>
    <section className="surface-card p-5 sm:p-6"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-semibold">Purchase reviews</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Verified-order feedback, moderation, and homepage placement.</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--text-soft)]"/><input className="field pl-9" value={query} onChange={e => { setQuery(e.target.value); setPage(1); }} placeholder="Search reviewer or purchase" /></label><select className="field" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div></div>
      {feedback ? <p className="mt-4 text-sm text-[var(--text-muted)]" role="status">{feedback}</p> : null}
      <div className="mt-5 grid gap-3">{data?.reviews.map(review => <article key={review.id} className="surface-list-item p-4"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong>{review.user.name}</strong><span className="rounded-full border px-2 py-1 text-[10px] font-semibold uppercase tracking-wider" style={{ borderColor: "var(--border)" }}>{review.status}</span>{review.featured ? <span className="rounded-full bg-[var(--accent)] px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-[var(--accent-contrast)]">Homepage</span> : null}</div><p className="mt-1 text-xs text-[var(--text-soft)]">{review.user.email} · {review.purchaseType} · {review.purchaseLabel} · {new Date(review.createdAt).toLocaleString("en-IN")}</p><div className="mt-3 flex gap-1" aria-label={`${review.rating} out of 5 stars`}>{[1,2,3,4,5].map(value => <Star key={value} className="h-4 w-4" color="#e5a72f" fill={value <= review.rating ? "#e5a72f" : "none"}/>)}</div><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--text-muted)]">{review.body || <em>No written feedback supplied.</em>}</p></div><div className="flex shrink-0 flex-wrap gap-2"><button className="btn-outline pressable px-3 py-2 text-xs" disabled={isPending} onClick={() => update(review.id,{status:"approved"})}><CheckCircle2 className="mr-1 inline h-3.5 w-3.5"/>Approve</button><button className="btn-outline pressable px-3 py-2 text-xs" disabled={isPending} onClick={() => update(review.id,{status:"rejected"})}><XCircle className="mr-1 inline h-3.5 w-3.5"/>Reject</button><button className="btn-primary pressable px-3 py-2 text-xs" disabled={isPending || review.status !== "approved" || !review.body} title={!review.body ? "Written feedback is required for homepage placement" : undefined} onClick={() => update(review.id,{featured:!review.featured})}>{review.featured ? "Remove from homepage" : "Feature on homepage"}</button></div></div></article>)}{data && !data.reviews.length ? <p className="py-10 text-center text-sm text-[var(--text-muted)]">No reviews match these filters.</p> : null}</div>
      {data && data.page.pages > 1 ? <div className="mt-5 flex items-center justify-between"><button className="btn-outline px-3 py-2 text-sm" disabled={page <= 1} onClick={() => setPage(value => value - 1)}>Previous</button><span className="text-xs text-[var(--text-soft)]">Page {data.page.current} of {data.page.pages}</span><button className="btn-outline px-3 py-2 text-sm" disabled={page >= data.page.pages} onClick={() => setPage(value => value + 1)}>Next</button></div> : null}
    </section>
  </div>;
}
