"use client";

import { useCallback, useEffect, useState, useTransition } from "react";

type Discrepancy = { id: number; field: string; hymnValue: unknown; direNoteValue: unknown; severity: string; status: string; detectedAt: string; release: { id: number; title: string; artistName: string }; track?: { id: number; title: string } | null };
const value = (item: unknown) => item == null ? "—" : typeof item === "string" ? item : JSON.stringify(item);

export function DireNoteReconciliationPanel() {
  const [filter, setFilter] = useState("open"); const [items, setItems] = useState<Discrepancy[]>([]); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const load = useCallback(async () => { const response = await fetch(`/api/admin/direnote/reconciliation${filter === "all" ? "" : `?status=${filter}`}`, { cache: "no-store" }); const data = await response.json().catch(() => ({})); setItems(Array.isArray(data.discrepancies) ? data.discrepancies : []); }, [filter]);
  useEffect(() => { void load(); }, [load]);
  const resolve = (id: number, resolution: "keep_hymn" | "accept_direnote" | "resolved") => startTransition(async () => { setMessage(""); const response = await fetch("/api/admin/direnote/reconciliation", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, resolution }) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? "Reconciliation decision saved." : data.error || "Could not save the decision."); if (response.ok) await load(); });
  return <section className="surface-card mt-6 p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-semibold">Reconciliation</h2><p className="mt-2 text-sm" style={{ color: "var(--text-muted)" }}>Compare HYMN&apos;s submitted metadata with the latest cached DireNote response. Legal metadata is never overwritten automatically.</p></div><select className="field w-auto" value={filter} onChange={(event) => setFilter(event.target.value)} aria-label="Filter reconciliation issues"><option value="all">All</option><option value="open">Open</option><option value="resolved">Resolved</option></select></div>{message ? <p className="mt-4 text-sm" aria-live="polite">{message}</p> : null}<div className="mt-5 grid gap-3">{items.map((item) => <article key={item.id} className="rounded-xl border p-4" style={{ borderColor: item.severity === "critical" ? "var(--danger)" : "var(--border)", background: "var(--bg-soft)" }}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{item.release.title} <span style={{ color: "var(--text-muted)" }}>· {item.track?.title || "Release"}</span></p><p className="mt-1 text-xs uppercase tracking-[0.14em]" style={{ color: "var(--text-soft)" }}>{item.field.replace(/_/g, " ")} · {item.severity} · {new Date(item.detectedAt).toLocaleString()}</p></div><span className="status-pill capitalize">{item.status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 text-sm"><div><p className="text-xs font-semibold uppercase tracking-[0.12em]" style={{ color: "var(--text-soft)" }}>HYMN</p><p className="mt-1 break-words">{value(item.hymnValue)}</p></div><div><p className="text-xs font-semibold uppercase tracking-[0.12em]" style={{ color: "var(--text-soft)" }}>DireNote</p><p className="mt-1 break-words">{value(item.direNoteValue)}</p></div></div>{item.status === "open" ? <div className="mt-4 flex flex-wrap gap-2"><button disabled={pending} type="button" className="btn-outline pressable text-xs" onClick={() => resolve(item.id, "keep_hymn")}>Keep HYMN value</button><button disabled={pending} type="button" className="btn-outline pressable text-xs" onClick={() => resolve(item.id, "accept_direnote")}>Accept DireNote value</button><button disabled={pending} type="button" className="btn-primary pressable text-xs" onClick={() => resolve(item.id, "resolved")}>Mark reviewed</button></div> : null}</article>)}{items.length === 0 ? <p className="rounded-xl border p-5 text-sm" style={{ borderColor: "var(--border)", color: "var(--text-muted)" }}>No reconciliation discrepancies match this filter.</p> : null}</div></section>;
}
