"use client";
import { useCallback, useEffect, useState, useTransition } from "react";
type Identity = { id: number; name: string; providerId: string; syncedAt: string | null; type: "artist" | "songwriter" };
export function DireNoteIdentitySyncPanel() {
  const [rows, setRows] = useState<Identity[]>([]); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const load = useCallback(async () => { const response = await fetch("/api/admin/direnote/identities", { cache: "no-store" }); const data = await response.json().catch(() => ({})); setRows([...(Array.isArray(data.artists) ? data.artists.map((row: any) => ({ id: row.id, name: row.artistName, providerId: row.direNoteArtistId, syncedAt: row.direNoteLastSyncedAt, type: "artist" as const })) : []), ...(Array.isArray(data.songwriters) ? data.songwriters.map((row: any) => ({ id: row.id, name: row.professionalName, providerId: row.direNoteSongwriterId, syncedAt: row.direNoteLastSyncedAt, type: "songwriter" as const })) : [])]); }, []);
  useEffect(() => { void load(); }, [load]);
  const refresh = (row: Identity) => startTransition(async () => { setMessage(""); const response = await fetch("/api/admin/direnote/identities", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: row.type, id: row.id }) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? `${row.name} was refreshed from DireNote.` : data.error || "Identity refresh failed."); if (response.ok) await load(); });
  return <section className="surface-card mt-6 p-5 sm:p-7"><h2 className="text-2xl font-semibold">Provider identities</h2><p className="mt-2 text-sm" style={{ color: "var(--text-muted)" }}>Refresh linked artist and songwriter records without replacing verified HYMN data.</p>{message ? <p className="mt-4 text-sm" aria-live="polite">{message}</p> : null}<div className="mt-5 grid gap-2">{rows.length ? rows.map(row => <div key={`${row.type}-${row.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3" style={{ borderColor: "var(--border-subtle)" }}><div><strong>{row.name}</strong><p className="text-xs" style={{ color: "var(--text-muted)" }}>{row.type === "artist" ? "Artist" : "Songwriter / composer"} · DNM {row.providerId} · {row.syncedAt ? new Date(row.syncedAt).toLocaleString("en-IN") : "Never refreshed"}</p></div><button className="btn-outline pressable" disabled={pending} onClick={() => refresh(row)}>Refresh</button></div>) : <p className="text-sm" style={{ color: "var(--text-muted)" }}>No DireNote identities have been linked yet.</p>}</div></section>;
}
