"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ChevronDown, Clock3, LifeBuoy, Search, Star } from "lucide-react";

type Article = { id: string; category: string; question: string; answer: string; tags: string; updated?: boolean };

export const faqArticles: Article[] = [
  { id: "account-access", category: "Accounts", question: "Why can’t I access my account or expected dashboard?", answer: "Sign in with the same email and method used to create the account. HYMN routes customers, producers, and administrators to role-specific workspaces. If the role is wrong or access remains unavailable, contact support from the account email.", tags: "login google password role dashboard account" },
  { id: "google-login", category: "Accounts", question: "How does Google authentication work?", answer: "Google authentication uses the selected Google account to identify you and establish a HYMN session. HYMN receives the account information needed for sign-in; it does not receive your Google password.", tags: "google oauth authentication privacy password" },
  { id: "plans", category: "Plans & Payments", question: "Which distribution plans are available?", answer: "HYMN currently presents One-Time Review, Half-Yearly, Yearly, and Yearly+ options. The checkout shows the current price, duration, artist-profile limit, label controls, and included workflow benefits before payment.", tags: "subscription plan one time half yearly annual yearly plus price", updated: true },
  { id: "payment-verification", category: "Plans & Payments", question: "What happens after I complete payment?", answer: "Razorpay returns a payment result to HYMN for server-side verification. A release is submitted only after verification succeeds. Keep the order and payment references if your bank shows a debit but HYMN does not show confirmation.", tags: "razorpay payment verification charged order" },
  { id: "refunds", category: "Plans & Payments", question: "When can I receive a refund?", answer: "Eligibility depends on whether payment was duplicated, failed after debit, or whether HYMN has already started the purchased review or fulfilment. A store rejection does not automatically create a refund. Submit the payment reference for review.", tags: "refund duplicate payment failed debit rejected" },
  { id: "release-submit", category: "Distribution", question: "How do I submit a release?", answer: "Choose the release type, add each recording, complete contributors and metadata, upload compliant artwork and audio, select destinations, review the summary, accept the declarations, and complete any required payment.", tags: "release upload distribute single ep album" },
  { id: "release-review", category: "Distribution", question: "Why is my release still under review?", answer: "The Review Queue checks metadata, artwork, audio quality, ownership declarations, contributor information, identifiers, and destination readiness. A release stays in review until the required checks are complete or HYMN requests corrections.", tags: "review queue pending qc status", updated: true },
  { id: "release-rejected", category: "Distribution", question: "What happens if my release is rejected or needs changes?", answer: "Open Manage Release and review the recorded decision and field-level corrections. Update the source fields and resubmit. Rejection does not automatically delete the release record or its review history.", tags: "rejected correction resubmit redressal changes" },
  { id: "distribution-processing", category: "Distribution", question: "What happens after HYMN approval or submission?", answer: "After HYMN approval, the release is validated and handed to HYMN's distribution network for processing. Store delivery and availability remain subject to each destination. HYMN records status updates such as distributor processing, scheduled, partially live, or live.", tags: "distribution delivery live status", updated: true },
  { id: "release-edits", category: "Distribution", question: "Can I edit a submitted release?", answer: "Submitted releases cannot be edited as freely as drafts. Where available, use Manage Release to submit a tracked metadata change request. HYMN reviews feasibility because stores may restrict changes after delivery.", tags: "edit submitted release change request manage" },
  { id: "duplicate-release", category: "Distribution", question: "Can I duplicate a release?", answer: "The release workspace may allow an existing release to be duplicated into a new draft. Review every field before submitting; identifiers and dates must reflect whether the new submission is genuinely the same catalog product.", tags: "duplicate copy release draft" },
  { id: "takedowns", category: "Distribution", question: "Can I delete or take down a release?", answer: "Draft deletion and a post-delivery takedown are different. For delivered content, submit a tracked takedown request with scope, destinations or territories, reason, and authorization. Store removal is not immediate and historical records may be retained.", tags: "delete release takedown remove stores" },
  { id: "upc", category: "Metadata", question: "What is a UPC and when do I receive it?", answer: "A UPC identifies a release as a catalog product across digital stores. For a new release, it is assigned through the distribution workflow after acceptance. If the release was distributed before, enter its existing official UPC to preserve catalog identity.", tags: "upc barcode identifier release distribution" },
  { id: "isrc", category: "Metadata", question: "What is an ISRC and when do I receive it?", answer: "An ISRC identifies an individual sound recording. New recordings receive identifiers through the accepted distribution workflow. Previously released recordings should reuse their official ISRC when the recording is unchanged.", tags: "isrc track recording identifier" },
  { id: "metadata", category: "Metadata", question: "Why does metadata validation matter?", answer: "Stores rely on exact titles, artist roles, language, genre, credits, ownership, explicit-content status, and release dates. HYMN validates required fields and consistency before distributor handoff to reduce avoidable rejections and catalog mismatches.", tags: "metadata title artist genre mood language credits" },
  { id: "contributors", category: "Metadata", question: "How should I enter contributors and artist profiles?", answer: "Credit every contributor using the role that reflects their actual participation. Link the correct artist profile where available and avoid creating duplicate identities. Contributors do not receive a payout share unless a royalty split is separately configured.", tags: "contributors artist profile roles credits splits" },
  { id: "artwork", category: "Uploads", question: "What artwork can I upload?", answer: "Upload the square image format and size shown in the artwork uploader. The artwork must be clear, authorized, consistent with the metadata, and free from misleading store badges, contact details, URLs, or unlicensed imagery.", tags: "artwork cover jpeg png square rights" },
  { id: "audio", category: "Uploads", question: "What audio should I upload?", answer: "Upload the final master requested by the release form, preferably a high-quality WAV where supported. Each track must match its title and sequence and must not contain clipping, corruption, unauthorized samples, or placeholder audio.", tags: "audio wav master upload quality" },
  { id: "cover-songs", category: "Copyright", question: "Can I distribute a cover song?", answer: "Only if you hold every licence and permission required for the composition, recording, territories, and uses you select. Upload or retain supporting evidence when requested. A cover licence does not authorize use of another party’s master recording.", tags: "cover song mechanical license copyright" },
  { id: "ai-content", category: "Copyright", question: "Can I upload AI-generated music?", answer: "AI-assisted content must be disclosed where the release flow requests it. You must have commercial rights to every generated or uploaded element and must not imitate protected artists, submit deceptive identities, or use prompts, voices, samples, or artwork you are not authorized to exploit.", tags: "ai generated suno disclosure synthetic voice", updated: true },
  { id: "content-id", category: "Copyright", question: "Who can use YouTube Content ID?", answer: "Content ID requires exclusive and sufficiently original rights. Do not enable it for non-exclusive beats, broadly licensed loops, public-domain recordings, content already enrolled elsewhere, or material likely to create conflicting claims. HYMN may request evidence or deny delivery.", tags: "youtube content id ugc claims exclusive" },
  { id: "ownership", category: "Copyright", question: "Do I keep my copyrights?", answer: "Yes. You retain the rights you own. You grant HYMN and its distribution partners only the permissions needed to store, review, process, deliver, display, report, monetize, and administer the selected services, subject to the applicable terms.", tags: "copyright ownership license non exclusive" },
  { id: "beat-licensing", category: "Beat Store", question: "How does Beat Store licensing work?", answer: "A buyer selects an available licence tier and completes payment. HYMN records the purchase and provides a private licence document and authorized deliverables when fulfilment is complete. The producer retains underlying rights except where the selected written licence states otherwise.", tags: "beat purchase license producer exclusive nonexclusive" },
  { id: "producer-sales", category: "Beat Store", question: "How are producer sales and earnings recorded?", answer: "Verified Beat Store purchases appear in the Producer Dashboard and finance records. Availability depends on successful payment verification and fulfilment. Refunds, disputes, fraud holds, and administrative corrections may affect the payable amount.", tags: "producer sales earnings finance beat store" },
  { id: "splits", category: "Royalties & Splits", question: "How are royalty splits calculated?", answer: "A release owner creates explicit percentages and invites recipients by registered email or temporary join code. Accepted shares are applied to matched royalty line items. HYMN does not infer percentages from contributor credits.", tags: "royalty split invite collaborator percentage", updated: true },
  { id: "royalty-imports", category: "Royalties & Splits", question: "How are royalties imported?", answer: "Authorized administrators upload distributor revenue reports. HYMN validates rows, prevents duplicate imports, matches statements to releases and recordings, preserves provenance, and routes unmatched rows to reconciliation before they can affect balances.", tags: "royalty import csv excel distribution reconciliation ledger", updated: true },
  { id: "revenue-reflection", category: "Royalties & Splits", question: "How does revenue reflection work?", answer: "After an import is validated and matched, HYMN records immutable royalty line items, applies eligible split rules, and reflects the resulting amounts in the Royalty Ledger and payout balances. The dashboard does not estimate unreported store revenue.", tags: "revenue reflection ledger dashboard earnings", updated: true },
  { id: "quarterly-payouts", category: "Payouts", question: "How do quarterly payouts work?", answer: "HYMN groups royalty and split activity into calendar quarters. Administrators resolve unmatched rows, generate reports, close and lock the period, carry forward unpaid available balances, and publish downloadable statements. A closed quarter preserves its ledger history.", tags: "quarterly payout report statement carry forward", updated: true },
  { id: "payout-pending", category: "Payouts", question: "Why is my payout pending or unavailable?", answer: "A request can remain unavailable or pending because funds are not yet available, the minimum threshold is unmet, payout details or KYC need review, another request is active, a balance is held, or administrative processing is incomplete.", tags: "payout pending unavailable threshold hold" },
  { id: "kyc", category: "Payouts", question: "Why does HYMN review payout verification details?", answer: "HYMN reviews payout identity and bank or UPI details to reduce misdirected payments, fraud, and compliance risk. Sensitive details are restricted in administrative views. Approval of a payout profile does not guarantee that every payout request will be approved.", tags: "kyc payout verification bank upi identity" },
  { id: "fraud-review", category: "Security", question: "Why can an account, release, or payout be placed under fraud review?", answer: "HYMN records risk alerts for suspicious payments, streaming or royalty patterns, rights conflicts, identity issues, abuse, and operational anomalies. Authorized administrators investigate cases and record actions. A flag is a review signal, not an automatic finding of wrongdoing.", tags: "fraud detection risk alert suspension review", updated: true },
  { id: "notifications", category: "Notifications", question: "When does HYMN send notifications or email?", answer: "HYMN may send in-product and transactional email updates for release decisions, correction requests, distribution status, split invitations, payment or licence fulfilment, payout events, and account operations. Delivery can be delayed by mail providers.", tags: "notifications email status unread" },
  { id: "referral-program", category: "Referrals & Credits", question: "What is the HYMN Referral Program?", answer: "It lets an eligible user invite a new artist with a permanent code or link. After the new account completes its first eligible paid purchase, HYMN adds ₹5 referral credit to the referrer and ₹3 HYMN release credit to the referred account.", tags: "referral program credit invite reward" },
  { id: "referral-how", category: "Referrals & Credits", question: "How do I refer someone?", answer: "Open Referrals in your dashboard and copy your code or referral link. You can also use Share on supported mobile devices. Your friend must use the link or apply the code while creating a new account.", tags: "refer share link code" },
  { id: "referral-friend-reward", category: "Referrals & Credits", question: "What does my friend receive?", answer: "Your friend receives ₹3 HYMN release credit after their first eligible paid purchase is verified. No credit is issued merely for opening the link, applying the code, or registering.", tags: "friend referred reward three rupees" },
  { id: "referral-rewards", category: "Referrals & Credits", question: "When do I receive my referral reward?", answer: "HYMN issues the ₹5 reward only after the referred account's first eligible paid purchase is verified by the server. Failed, zero-value, refunded, test, administrative, and duplicated payment events do not qualify.", tags: "reward eligibility payment verified" },
  { id: "referral-pending", category: "Referrals & Credits", question: "What is a pending referral?", answer: "A pending referral has joined HYMN with your attribution but has not completed the qualifying paid activity. Pending credit is not spendable.", tags: "pending joined qualification" },
  { id: "referral-qualified", category: "Referrals & Credits", question: "What qualifies a referral?", answer: "The default qualifying event is the referred account's first successful eligible paid purchase, such as an eligible distribution purchase. The payment must be genuine, positive-value, and verified server-side.", tags: "qualified qualifying purchase distribution" },
  { id: "referral-withdraw", category: "Referrals & Credits", question: "Can I withdraw referral credit?", answer: "No. Referral rewards and HYMN release credit are promotional platform credits, not cash, royalty earnings, or a withdrawable producer balance.", tags: "withdraw cash royalties credit" },
  { id: "referral-use", category: "Referrals & Credits", question: "Can I use referral credit for distribution?", answer: "Eligible HYMN credit can be applied at checkout, including partial credit. HYMN validates the balance and records the redemption on the server.", tags: "use distribution checkout partial balance" },
  { id: "referral-existing", category: "Referrals & Credits", question: "Can I refer an existing HYMN user?", answer: "No. Attribution is intended for genuinely new accounts and is locked during signup or new-account onboarding. An established account cannot attach a referrer later.", tags: "existing account eligibility" },
  { id: "referral-self", category: "Referrals & Credits", question: "Can I refer myself?", answer: "No. Self-referrals, circular referrals, duplicate identities, and account farming are ineligible and may be sent for review.", tags: "self referral circular abuse" },
  { id: "referral-refund", category: "Referrals & Credits", question: "What happens if the qualifying payment is refunded?", answer: "HYMN records a reversal rather than deleting the original reward. If credited value was already spent, the referral is placed in administrative review instead of creating a silently corrupted negative balance.", tags: "refund chargeback reversal" },
  { id: "referral-review", category: "Referrals & Credits", question: "Why was my referral marked for review?", answer: "A review means the system detected a risk signal such as circular activity, repeated payment identity, unusual volume, or a refund after reward. It is not an automatic finding of fraud.", tags: "review fraud signal abuse" },
  { id: "referral-history", category: "Referrals & Credits", question: "Where can I see my referral history?", answer: "Open Customer Dashboard → Referrals to see masked referral status, earned credit, available credit, and immutable credit history.", tags: "history dashboard ledger" },
  { id: "subscription-expiry", category: "Plans & Payments", question: "What happens when a subscription expires?", answer: "Expiry ends the active subscription benefits and allowances shown for that plan. Existing records remain in the account, but new submissions or plan-gated actions may require renewal or a separate eligible payment. Store availability is governed by the applicable distribution terms.", tags: "subscription expires renewal releases" },
  { id: "privacy-security", category: "Security", question: "How does HYMN protect private files and account data?", answer: "HYMN uses authenticated sessions, role-based permissions, private asset download routes, audit records, validation, and operational access controls. No online service can guarantee absolute security; report suspected account misuse promptly.", tags: "privacy security private assets permissions" }
];

const popularIds = ["release-review", "upc", "royalty-imports", "quarterly-payouts", "payout-pending", "beat-licensing"];

export function FaqCenter() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [openId, setOpenId] = useState<string | null>(null);
  const [highlightId, setHighlightId] = useState<string | null>(null);
  const categories = ["All", ...Array.from(new Set(faqArticles.map((article) => article.category)))];

  useEffect(() => {
    const openHash = () => {
      const id = decodeURIComponent(window.location.hash.slice(1));
      if (!id || !faqArticles.some((article) => article.id === id)) return;
      setQuery(""); setCategory("All"); setOpenId(id); setHighlightId(id);
      window.setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "center" }), 60);
      window.setTimeout(() => document.getElementById(`${id}-trigger`)?.focus({ preventScroll: true }), 520);
      window.setTimeout(() => setHighlightId(null), 2000);
    };
    openHash();
    window.addEventListener("hashchange", openHash);
    return () => window.removeEventListener("hashchange", openHash);
  }, []);

  const shown = useMemo(() => {
    const term = query.trim().toLowerCase();
    return faqArticles.filter((article) => (category === "All" || article.category === category) && (!term || `${article.question} ${article.answer} ${article.tags} ${article.category}`.toLowerCase().includes(term)));
  }, [query, category]);

  const renderArticle = (article: Article) => {
    const open = openId === article.id;
    return (
      <article id={article.id} key={article.id} className={`faq-article surface-card overflow-hidden ${highlightId === article.id ? "faq-article-highlight" : ""}`}>
        <h3>
          <button id={`${article.id}-trigger`} type="button" className="flex w-full items-start justify-between gap-4 p-5 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset" aria-expanded={open} aria-controls={`${article.id}-panel`} onClick={() => setOpenId(open ? null : article.id)}>
            <span><span className="chip">{article.category}</span><span className="mt-3 block text-lg font-semibold">{article.question}</span></span>
            <ChevronDown className={`mt-1 h-5 w-5 shrink-0 transition-transform ${open ? "rotate-180" : ""}`} aria-hidden="true" />
          </button>
        </h3>
        {open ? <div id={`${article.id}-panel`} role="region" aria-labelledby={`${article.id}-trigger`} className="border-t p-5 text-sm leading-7" style={{ borderColor: "var(--border)", color: "var(--text-muted)" }}>{article.answer}</div> : null}
      </article>
    );
  };

  return (
    <div className="space-y-8">
      <section className="surface-card p-5 sm:p-6">
        <div className="flex items-center gap-3"><LifeBuoy aria-hidden="true" /><div><h2 className="text-2xl font-semibold">HYMN Help Center</h2><p className="text-sm" style={{ color: "var(--text-muted)" }}>Search platform guidance by workflow or question.</p></div></div>
        <div className="relative mt-5"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2" aria-hidden="true" /><input className="field pl-12" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search FAQ..." aria-label="Search FAQ" /></div>
        <div className="mt-4 flex flex-wrap gap-2" aria-label="FAQ categories">{categories.map((item) => <button key={item} type="button" className="rounded-full border px-3 py-2 text-xs font-medium" style={{ borderColor: category === item ? "var(--accent)" : "var(--border)", background: category === item ? "var(--accent-soft)" : "var(--card)" }} aria-pressed={category === item} onClick={() => setCategory(item)}>{item}</button>)}</div>
      </section>

      {!query && category === "All" ? <div className="grid gap-6 lg:grid-cols-2"><section><h2 className="mb-3 flex items-center gap-2 text-xl font-semibold"><Star className="h-5 w-5" aria-hidden="true" /> Popular Questions</h2><div className="grid gap-3">{faqArticles.filter((article) => popularIds.includes(article.id)).map(renderArticle)}</div></section><section><h2 className="mb-3 flex items-center gap-2 text-xl font-semibold"><Clock3 className="h-5 w-5" aria-hidden="true" /> Recently Updated</h2><div className="grid gap-3">{faqArticles.filter((article) => article.updated).slice(0, 6).map(renderArticle)}</div></section></div> : null}

      <section aria-live="polite"><h2 className="mb-3 text-xl font-semibold">{query || category !== "All" ? `${shown.length} result${shown.length === 1 ? "" : "s"}` : "All Questions"}</h2><div className="grid gap-3">{shown.map(renderArticle)}{shown.length === 0 ? <div className="surface-card p-8 text-center"><h3 className="text-xl font-semibold">No matching answer found</h3><p className="mt-2" style={{ color: "var(--text-muted)" }}>Try another term or send the relevant account, release, payment, payout, or purchase reference to support.</p><Link href="/contact" className="btn-primary mt-5">Contact Support</Link></div> : null}</div></section>
    </div>
  );
}
