"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ChevronDown, LifeBuoy, Search } from "lucide-react";

type Article = { id: string; module: string; question: string; answer: string; tags: string; steps?: string[] };
const articles: Article[] = [
  { id:"google-login", module:"Account / Login", question:"Google login or account access is not working", answer:"Use the same Google account originally linked to HYMN, allow cookies, and retry in a private window. Role access controls which dashboard appears; contact support if your artist or producer role is missing.", tags:"login google login account access role switching dashboard producer rights", steps:["Confirm the Google email used for HYMN.","Retry after allowing cookies and pop-ups.","Include the email and screenshot in a support ticket if access is still blocked."] },
  { id:"release-upload", module:"Distribution Portal", question:"How do I upload and submit a release?", answer:"Choose Single, EP, or Album, upload one master per track, complete contributors and metadata, add compliant artwork, select destinations, review the summary, and complete payment.", tags:"upload release release types audio upload contributors language genre release date" },
  { id:"already-released", module:"Distribution Portal", question:"My music was already released—what identifiers do I use?", answer:"Select Already released: Yes and enter the official UPC for the release and ISRC for the recording. Reusing the original identifiers helps stores preserve catalog identity and stream history.", tags:"already released previously distributed isrc upc identifiers metadata" },
  { id:"requirements", module:"Distribution Portal", question:"What are the artwork and audio requirements?", answer:"Use a clean square JPG/PNG cover at the dimensions shown in the uploader and a high-quality WAV master where possible. Do not include unauthorized logos, URLs, blurry images, clipped audio, or misleading metadata.", tags:"artwork cover jpg png audio wav upload requirements" },
  { id:"rejected", module:"Admin / Review", question:"Release rejected or changes requested", answer:"Open Your Releases, select the affected release, and open its redressal panel. Correct every marked field—such as UPC, ISRC, credits, artwork, audio, language, genre, or date—then resubmit.", tags:"release rejected metadata corrections redressal admin review direnote changes requested", steps:["Open the notification or Your Releases.","Read every marked field and admin note.","Correct the source fields, review the summary, and resubmit."] },
  { id:"direnote", module:"Distribution Portal", question:"What does sent to DireNote mean?", answer:"HYMN review has passed and the release has been handed to the distribution partner. Processing and store delivery can still take time; watch the release page and notifications for updates.", tags:"direnote submission sent processing distribution live" },
  { id:"payment", module:"Payments / Subscription", question:"Payment failed or confirmation is missing", answer:"A failed Razorpay payment does not submit the release. Retry from the saved draft and avoid paying twice. If money was debited without confirmation, create a ticket with the payment ID; verification or reversal can take bank processing time.", tags:"payment failed razorpay invoice confirmation one-time subscription plan", steps:["Check whether the release remains a draft.","Save the Razorpay payment/order ID.","Retry only if no successful confirmation exists; otherwise contact support."] },
  { id:"subscription", module:"Payments / Subscription", question:"How do subscriptions and one-time release payments work?", answer:"Choose the one-time release option or an available subscription at checkout. The selected plan controls allowance and pricing; payment confirmation appears after gateway verification.", tags:"subscription annual half yearly one time payment invoice plan" },
  { id:"earnings", module:"Payout / Earnings", question:"Earnings are not visible yet", answer:"Verified royalty data commonly takes around 1.5 months to appear because stores report after the listening period. If a completed reporting period is still missing, send the release and statement details to support.", tags:"earnings not visible royalties 1.5 months reports" },
  { id:"payout", module:"Payout / Earnings", question:"How do payout requests work?", answer:"Request an eligible balance from Payout and choose UPI or bank transfer. Processing is normally 24–48 hours after review. The displayed calculation includes the applicable 2% service fee.", tags:"payout request 24 48 hours 2% service fee upi bank transfer" },
  { id:"beat-license", module:"Beat Store", question:"Beat purchase or license is missing", answer:"Open Dashboard → Purchases and select the order. A license appears after the producer uploads it. If access was revoked or the file remains missing, create a ticket with the purchase ID.", tags:"beat purchase license download missing license access revoked restored exclusive", steps:["Open Dashboard and choose Purchases.","Confirm payment and access status.","Send the purchase ID to support if the license is unavailable."] },
  { id:"producer", module:"Producer Dashboard", question:"Producer approval, beat management, and sales", answer:"After producer approval, use Producer Dashboard to upload and manage beats, attach licenses, and review sales and earnings. A rejected application stays out of producer-only tools until approved.", tags:"producer dashboard approval rejection upload beats manage beats sales reports earnings license management" },
  { id:"notifications", module:"Notifications", question:"How do notification read states and links work?", answer:"Unread items show a badge. Mark all as read clears it; opening an item marks it read and takes you to the related release, payout, purchase, or producer module when a link is available.", tags:"notification unread mark read badge cta link meaning" },
  { id:"referral", module:"Referral", question:"Referral credit or history is not visible", answer:"Share the referral link from your dashboard. Credits appear only after the qualifying event is verified. Check referral history first, then contact support with the invited email if a verified credit is missing.", tags:"referral link credits history credit not visible" }
];
const popular = ["rejected", "payment", "payout", "beat-license", "google-login"];

export function FaqCenter() {
  const [query,setQuery]=useState(""); const [module,setModule]=useState("All"); const [open,setOpen]=useState<string|null>("rejected");
  const modules=["All",...Array.from(new Set(articles.map(a=>a.module)))];
  const shown=useMemo(()=>{const q=query.trim().toLowerCase(); return articles.filter(a=>(module==="All"||a.module===module)&&(!q||`${a.question} ${a.answer} ${a.tags} ${a.module}`.toLowerCase().includes(q)));},[query,module]);
  const render=(a:Article)=><article key={a.id} className="surface-card overflow-hidden"><button type="button" className="flex w-full items-start justify-between gap-4 p-5 text-left" onClick={()=>setOpen(open===a.id?null:a.id)}><span><span className="chip">{a.module}</span><h3 className="mt-3 text-lg font-semibold">{a.question}</h3></span><ChevronDown className={`h-5 w-5 shrink-0 transition ${open===a.id?"rotate-180":""}`}/></button>{open===a.id?<div className="border-t p-5 text-sm leading-7" style={{borderColor:"var(--border)",color:"var(--text-muted)"}}><p>{a.answer}</p>{a.steps?<ol className="mt-4 list-decimal space-y-2 pl-5">{a.steps.map(s=><li key={s}>{s}</li>)}</ol>:null}</div>:null}</article>;
  return <div className="space-y-6"><section className="surface-card p-6"><div className="flex items-center gap-3"><LifeBuoy/><div><h2 className="text-2xl font-semibold">HYMN Support Center</h2><p className="text-sm" style={{color:"var(--text-muted)"}}>Search every major HYMN module and follow practical resolution steps.</p></div></div><div className="relative mt-5"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2"/><input autoFocus className="field pl-12" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search payment, release rejected, ISRC, payout, license…" aria-label="Search support articles"/></div><div className="mt-4 flex flex-wrap gap-2">{modules.map(m=><button key={m} className="rounded-full border px-3 py-2 text-xs" style={{borderColor:"var(--border)",background:module===m?"var(--accent-soft)":"var(--card)"}} onClick={()=>setModule(m)}>{m}</button>)}</div></section>{!query&&module==="All"?<section><h2 className="mb-3 text-xl font-semibold">Popular issues</h2><div className="grid gap-3 md:grid-cols-2">{articles.filter(a=>popular.includes(a.id)).map(render)}</div></section>:null}<section className="grid gap-3">{shown.map(render)}{shown.length===0?<div className="surface-card p-8 text-center"><h3 className="text-xl font-semibold">No exact result found.</h3><p className="mt-2" style={{color:"var(--text-muted)"}}>Create a support ticket and HYMN will help you resolve this.</p><Link href="/contact" className="btn-primary mt-5">Create support ticket</Link></div>:null}</section><section className="surface-card flex flex-col gap-4 p-6 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-semibold">Still need help?</h2><p className="mt-2 text-sm" style={{color:"var(--text-muted)"}}>Create a support ticket with the release, payment, payout, or purchase ID.</p></div><Link href="/contact" className="btn-primary">Create support ticket</Link></section></div>;
}
