"use client";
import { useState } from "react";
type ProviderStatus = { id: number; provider: string; status: string; reference?: string | null };
type Row = { id: number; serviceType: string; status: string; riskFlags?: string[] | null; eligibilityAnswers: Record<string, unknown>; user: { name: string; email: string }; release: { title: string; artistName: string }; documents: { asset: { id: number; safeFilename: string } }[]; providerStatuses?: ProviderStatus[] };
type Draft = { status: string; update: string; reference: string; notes: string; provider: string; providerStatus: string };
const statuses = ["eligibility_review", "information_required", "approved", "processing_manually", "submitted_to_partner", "completed", "partially_completed", "rejected", "cancelled", "failed"];
export function ManagedServiceReviewQueue({ initialRequests }: { initialRequests: Row[] }) {
  const [rows, setRows] = useState(initialRequests); const [drafts, setDrafts] = useState<Record<number, Draft>>({}); const [messages, setMessages] = useState<Record<number, string>>({});
  const draft = (row: Row): Draft => drafts[row.id] || { status: "eligibility_review", update: "", reference: "", notes: "", provider: "", providerStatus: "" };
  const patch = (row: Row, change: Partial<Draft>) => setDrafts(value => ({ ...value, [row.id]: { ...draft(row), ...change } }));
  async function save(row: Row) { const value = draft(row); setMessages(state => ({ ...state, [row.id]: "Saving..." })); const providerStatuses = value.provider && value.providerStatus ? [{ provider: value.provider, status: value.providerStatus, reference: value.reference || undefined, note: value.notes || undefined }] : undefined; const response = await fetch(`/api/admin/managed-services/${row.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: value.status, userVisibleUpdate: value.update, externalReference: value.reference || undefined, internalNotes: value.notes || undefined, providerStatuses }) }); const envelope = await response.json().catch(() => ({})); if (!response.ok || !envelope.success) { setMessages(state => ({ ...state, [row.id]: envelope.error?.message || "Update failed." })); return; } setRows(state => state.map(item => item.id === row.id ? { ...item, status: envelope.data.request.status } : item)); setMessages(state => ({ ...state, [row.id]: "Update recorded." })); }
  return <div className="mt-6 grid gap-4">{rows.map(row => <article className="surface-card" key={row.id}><div className="flex justify-between gap-3"><div><h2 className="text-xl font-semibold">{row.serviceType.replace(/_/g, " ")} · {row.release.title}</h2><p className="text-sm" style={{ color: "var(--text-muted)" }}>{row.user.name} · {row.user.email}</p></div><span className="status-pill capitalize">{row.status.replace(/_/g, " ")}</span></div>{Boolean(row.riskFlags?.length) && <p className="mt-3" style={{ color: "var(--danger)" }}>Risk flags: {row.riskFlags?.join(", ")}</p>}<details className="mt-3"><summary className="cursor-pointer font-semibold">Eligibility answers and declarations</summary><pre className="mt-2 overflow-x-auto whitespace-pre-wrap rounded-xl border p-3 text-xs" style={{ borderColor: "var(--border)" }}>{JSON.stringify(row.eligibilityAnswers, null, 2)}</pre></details><div className="mt-3">{row.documents.map(document => <a className="mr-4 underline" href={`/api/assets/${document.asset.id}/download`} key={document.asset.id}>{document.asset.safeFilename}</a>)}</div>{row.providerStatuses?.map(item => <p className="mt-2 text-sm" key={item.id}>{item.provider}: {item.status}{item.reference ? ` · ${item.reference}` : ""}</p>)}<div className="mt-4 grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm">Next workflow status<select className="input" value={draft(row).status} onChange={event => patch(row, { status: event.target.value })}>{statuses.map(status => <option key={status}>{status}</option>)}</select></label><label className="grid gap-1 text-sm">Partner reference<input className="input" value={draft(row).reference} onChange={event => patch(row, { reference: event.target.value })} /></label><label className="grid gap-1 text-sm">User-visible update<input className="input" value={draft(row).update} onChange={event => patch(row, { update: event.target.value })} /></label><label className="grid gap-1 text-sm">Internal evidence / notes<input className="input" value={draft(row).notes} onChange={event => patch(row, { notes: event.target.value })} /></label><label className="grid gap-1 text-sm">Telecom/provider status provider<input className="input" value={draft(row).provider} onChange={event => patch(row, { provider: event.target.value })} placeholder="e.g. Airtel" /></label><label className="grid gap-1 text-sm">Provider fulfilment status<input className="input" value={draft(row).providerStatus} onChange={event => patch(row, { providerStatus: event.target.value })} placeholder="e.g. submitted / active / rejected" /></label></div><button className="btn-primary pressable mt-3" onClick={() => save(row)}>Record manual update</button><p className="mt-2 text-sm" aria-live="polite">{messages[row.id]}</p></article>)}</div>;
}
// vercel trigger 9
