"use client";

import { forwardRef, useEffect, useMemo, useRef, useState, type CSSProperties, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowLeft, ArrowRight, X } from "lucide-react";
import { OnboardingLoginModal } from "@/components/onboarding-login-modal";
import { ONBOARDING_ROUTES, ONBOARDING_SEEN_KEY, ONBOARDING_STORAGE_KEY, beatStoreHref, saveOnboardingContext, type OnboardingContext } from "@/lib/onboarding-client";

type Step = "entry" | "name" | "hello" | "intent" | "releaseStage" | "releaseType" | "frequency" | "missing" | "previous" | "beginner" | "beatMood" | "beatGenre" | "beatBudget" | "producerStage" | "producerNeeds" | "promotionGoal" | "releaseTiming" | "exploreTopic" | "goal" | "source" | "result";
type Option = { value: string; title: string; detail?: string };

const intents: Option[] = [
  { value: "release", title: "Release my music", detail: "Get a release ready for stores." },
  { value: "beats", title: "Find the right beat", detail: "Shape a shelf around your sound." },
  { value: "producer", title: "Sell my beats", detail: "Explore storefront and licensing access." },
  { value: "promotion", title: "Grow an existing release", detail: "Find the most useful next move." },
  { value: "understand", title: "Understand how HYMN works", detail: "Take a quick guided tour." },
  { value: "explore", title: "I’m just exploring", detail: "Look around without pressure." }
];
const goals = ["Releasing my first song", "Building a catalogue", "Making money from music", "Finding my sound", "Reaching more listeners", "Becoming consistent"];
const sources = ["Instagram", "Artist or friend", "Google", "College or community", "YouTube", "Other"];

export function TypingText({ text, className = "", onDone }: { text: string; className?: string; onDone?: () => void }) {
  const reduced = useReducedMotion(); const [visible, setVisible] = useState(reduced ? text : ""); const done = useRef(false);
  useEffect(() => { done.current = false; if (reduced) { setVisible(text); onDone?.(); return; } setVisible(""); let i = 0; let timer: ReturnType<typeof setTimeout>; const tick = () => { i++; setVisible(text.slice(0, i)); if (i >= text.length) { if (!done.current) onDone?.(); done.current = true; return; } const char = text[i - 1]; timer = setTimeout(tick, /[.!?]/.test(char) ? 180 : 31); }; timer = setTimeout(tick, 80); return () => clearTimeout(timer); }, [onDone, reduced, text]);
  return <span className={className} aria-label={text}><span aria-hidden="true">{visible}</span><span className="sr-only">{text}</span></span>;
}

export function OnboardingExperience({ isAuthenticated }: { isAuthenticated: boolean }) {
  const router = useRouter(); const [step, setStep] = useState<Step>("entry"); const [history, setHistory] = useState<Step[]>([]); const [context, setContext] = useState<OnboardingContext>({}); const [name, setName] = useState(""); const [error, setError] = useState(""); const [login, setLogin] = useState<null | { title: string; body: string; href: string; secondary: string }>(null); const headingRef = useRef<HTMLHeadingElement>(null);
  useEffect(() => { try { const saved = localStorage.getItem(ONBOARDING_STORAGE_KEY); if (saved) { const parsed = JSON.parse(saved); setContext(parsed); setName(parsed.name || ""); } } catch { localStorage.removeItem(ONBOARDING_STORAGE_KEY); } }, []);
  useEffect(() => { if (step !== "entry") saveOnboardingContext(context); headingRef.current?.focus(); }, [context, step]);
  const routeSteps = useMemo(() => routeFor(context.primaryIntent), [context.primaryIntent]);
  const progress = step === "entry" ? 0 : step === "result" ? 100 : Math.max(8, Math.round(((routeSteps.indexOf(step) + 1) / (routeSteps.length + 2)) * 100));
  const progressColor = `hsl(${44 + progress * 0.86} 72% ${progress < 55 ? 48 : 42}%)`;
  const accent = context.primaryIntent === "beats" ? "#f5c16c" : context.primaryIntent === "producer" ? "#a78bfa" : context.primaryIntent === "promotion" ? "#fb7185" : "var(--accent)";
  function go(next: Step, update: OnboardingContext = {}) { setHistory(v => [...v, step]); setContext(v => ({ ...v, ...update })); setStep(next); setError(""); }
  function back() { const previous = history.at(-1); if (!previous) return; setHistory(v => v.slice(0, -1)); setStep(previous); }
  function answer(field: keyof OnboardingContext, value: string, next: Step) { go(next, { [field]: value }); }
  function finish(update: OnboardingContext = {}) { go("result", { ...update, onboardingCompleted: true }); }
  function navigate(href: string, requiresLogin?: { title: string; body: string; secondary: string }) { const next = { ...context, preferredRoute: href, onboardingCompleted: true }; saveOnboardingContext(next); localStorage.setItem(ONBOARDING_SEEN_KEY, "true"); if (!isAuthenticated && requiresLogin) setLogin({ ...requiresLogin, href }); else router.push(href); }

  const screen = getScreen(step, context, answer, go, finish);
  return <main className="fixed inset-0 z-[100] overflow-y-auto overflow-x-hidden bg-[var(--bg)]" style={{ "--onboarding-accent": accent } as CSSProperties}>
    <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_88%_12%,color-mix(in_srgb,var(--onboarding-accent)_16%,transparent),transparent_34%),radial-gradient(circle_at_8%_88%,color-mix(in_srgb,var(--onboarding-accent)_7%,transparent),transparent_30%)] transition-colors duration-700" />
    <div className="fixed inset-x-0 top-0 z-[110] h-1 bg-[var(--bg-soft)]"><div className="h-full transition-[width,background-color] duration-500" style={{ width: `${progress}%`, backgroundColor: progressColor }} /></div>
    <div className="relative mx-auto flex min-h-[100svh] max-w-5xl flex-col px-4 pb-[max(6rem,env(safe-area-inset-bottom))] pt-[max(1rem,env(safe-area-inset-top))] sm:px-7">
      <header className="flex min-h-14 items-center justify-between border-b border-[var(--border)]/70">
        <div className="flex min-w-[5.5rem] items-center"><button type="button" onClick={back} disabled={!history.length} className="inline-flex min-h-11 items-center gap-2 rounded-full px-2 text-sm font-semibold disabled:invisible focus-visible:ring-2"><ArrowLeft className="h-4 w-4" /> Back</button></div>
        <Image src="/assets/hymnlogowhite.png" alt="HYMN" width={116} height={38} className="h-7 w-auto object-contain" style={{ filter: "var(--logo-filter)" }} priority />
        <div className="flex min-w-[5.5rem] items-center justify-end gap-1"><span className="text-sm font-normal tabular-nums transition-colors duration-500" style={{ color: progressColor }} aria-label={`${progress} percent complete`}>{progress}%</span><button type="button" onClick={() => { localStorage.setItem(ONBOARDING_SEEN_KEY, "true"); router.push("/"); }} aria-label="Exit onboarding" className="grid min-h-11 min-w-11 place-items-center rounded-full focus-visible:ring-2"><X className="h-4 w-4" /></button></div>
      </header>
      <motion.section key={step} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="my-auto py-6">
        {step === "entry" ? <Entry onStart={() => go("name")} onLogin={() => { localStorage.setItem(ONBOARDING_SEEN_KEY, "true"); router.push("/login"); }} /> : step === "name" ? <div className="mx-auto max-w-xl"><QuestionTitle ref={headingRef}>What should we call you?</QuestionTitle><label className="mt-8 block"><span className="sr-only">Your name</span><input autoFocus value={name} onChange={e => { setName(e.target.value); setError(""); }} onKeyDown={e => { if (e.key === "Enter" && name.trim()) go("hello", { name: name.trim() }); }} placeholder="Your name or artist name" className="min-h-14 w-full rounded-2xl border bg-[var(--surface)] px-5 text-lg outline-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent)]/25" /></label>{error ? <p role="alert" className="mt-3 text-sm text-[var(--danger)]">{error}</p> : null}<Sticky><Primary onClick={() => name.trim() ? go("hello", { name: name.trim() }) : setError("Tell us what to call you.")}>Continue</Primary></Sticky></div> : step === "hello" ? <div className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-[var(--accent)]">Good to meet you, {context.name}.</p><QuestionTitle ref={headingRef} align="center"><TypingText text="Let’s figure out what gets your music moving." /></QuestionTitle><Sticky><Primary onClick={() => go("intent")}>Let’s go</Primary></Sticky></div> : step === "result" ? <Result context={context} navigate={navigate} /> : <div><QuestionTitle ref={headingRef}><TypingText text={screen.question} /></QuestionTitle>{screen.note ? <p className="mx-auto mt-3 max-w-2xl text-center text-sm leading-6 text-[var(--text-muted)]">{screen.note}</p> : null}{screen.steps ? <div className="mx-auto mt-8 grid max-w-xl gap-3">{screen.steps.map((value, i) => <motion.div key={value} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * .15 }} className="flex items-center gap-3 rounded-2xl border bg-[var(--surface)] p-4"><span className="grid h-8 w-8 place-items-center rounded-full bg-[var(--accent)] font-bold text-[var(--bg)]">{i + 1}</span>{value}</motion.div>)}</div> : <Options options={screen.options} selected={screen.selected} onSelect={screen.onSelect} />}{screen.action ? <Sticky><Primary onClick={screen.action.onClick}>{screen.action.label}</Primary></Sticky> : null}</div>}
      </motion.section>
    </div>
    <OnboardingLoginModal open={Boolean(login)} title={login?.title || "Log in to continue"} body={login?.body || "Your place will be saved."} redirectAfterLogin={login?.href || "/dashboard"} context={context} secondaryLabel={login?.secondary} onClose={() => { const href = login?.href; setLogin(null); if (href && login?.secondary === "Browse first") router.push(href); }} />
  </main>;
}

function Entry({ onStart, onLogin }: { onStart: () => void; onLogin: () => void }) { return <div className="mx-auto max-w-3xl text-center"><p className="text-[.68rem] font-bold uppercase tracking-[.28em] text-[var(--onboarding-accent)]">Your music starts here</p><h1 className="mt-5 text-[clamp(2.75rem,9vw,5.5rem)] font-semibold leading-[.96] tracking-[-.055em]">New to HYMN?</h1><p className="mx-auto mt-6 min-h-14 max-w-xl text-base leading-7 text-[var(--text-muted)] sm:text-xl"><TypingText text="Let’s find the fastest route for your music." /></p><div className="mx-auto mt-9 grid max-w-sm gap-3"><Primary onClick={onStart}>Yes, show me around</Primary><button onClick={onLogin} className="min-h-12 rounded-xl font-semibold text-[var(--text-muted)] transition hover:text-[var(--text)] focus-visible:ring-2">I already have an account</button></div></div>; }
const QuestionTitle = forwardRef<HTMLHeadingElement, { children: ReactNode; align?: "left" | "center" }>(function QuestionTitle({ children, align = "left" }, ref) { return <h1 ref={ref} tabIndex={-1} className={`mx-auto w-full max-w-3xl text-3xl font-semibold tracking-[-.035em] outline-none sm:text-[clamp(2.15rem,4vw,3rem)] md:whitespace-nowrap ${align === "center" ? "text-center" : "text-left"}`}>{children}</h1>; });

function Options({ options, selected, onSelect }: { options: Option[]; selected?: string; onSelect: (value: string) => void }) { return <motion.div initial="hidden" animate="show" variants={{ show: { transition: { staggerChildren: .045 } } }} className="mx-auto mt-8 grid max-w-3xl gap-x-12 gap-y-1 sm:grid-cols-2">{options.map(o => <motion.button variants={{ hidden: { opacity: 0, y: 8 }, show: { opacity: 1, y: 0 } }} key={o.value} type="button" onClick={() => onSelect(o.value)} aria-pressed={selected === o.value} className={`group relative flex min-h-[68px] items-center overflow-hidden px-1 py-3 text-left transition-[transform,opacity,color] duration-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--onboarding-accent)] focus-visible:ring-offset-4 focus-visible:ring-offset-[var(--bg)] active:scale-[.99] ${selected && selected !== o.value ? "opacity-35" : ""}`} style={{ color: selected === o.value ? "var(--onboarding-accent)" : "var(--text)" }}><span aria-hidden="true" className="pointer-events-none absolute inset-y-1 -left-1 w-2/3 -translate-x-[130%] skew-x-[-18deg] bg-gradient-to-r from-transparent via-white/[.09] to-transparent blur-sm transition-transform duration-700 ease-out group-hover:translate-x-[190%]" /><span aria-hidden="true" className="absolute inset-x-0 bottom-0 h-px origin-left scale-x-0 bg-gradient-to-r from-[var(--onboarding-accent)] via-[var(--onboarding-accent)]/45 to-transparent transition-transform duration-300 group-hover:scale-x-100" style={{ transform: selected === o.value ? "scaleX(1)" : undefined }} /><span className="relative min-w-0 flex-1"><strong className="block text-base font-semibold tracking-[-.015em] transition-[text-shadow] duration-300 group-hover:[text-shadow:0_0_22px_rgba(255,255,255,.22)] sm:text-lg">{o.title}</strong>{o.detail ? <span className="mt-1 block text-xs leading-5 text-[var(--text-muted)] transition-colors group-hover:text-[var(--text-soft)]">{o.detail}</span> : null}</span></motion.button>)}</motion.div>; }
function Primary({ children, onClick }: { children: ReactNode; onClick: () => void }) { return <button type="button" onClick={onClick} className="inline-flex min-h-12 w-full items-center justify-center gap-2 whitespace-nowrap rounded-xl bg-[var(--accent)] px-5 font-bold text-[var(--bg)] transition hover:-translate-y-0.5 focus-visible:ring-2 focus-visible:ring-offset-2 sm:w-auto">{children}<ArrowRight className="h-4 w-4" /></button>; }
function Sticky({ children }: { children: ReactNode }) { return <div className="fixed inset-x-0 bottom-0 z-30 border-t bg-[color-mix(in_srgb,var(--bg)_92%,transparent)] p-3 pb-[max(.75rem,env(safe-area-inset-bottom))] backdrop-blur-xl sm:static sm:mt-8 sm:border-0 sm:bg-transparent sm:p-0 sm:text-center">{children}</div>; }

function routeFor(intent?: string): Step[] { if (intent === "release") return ["intent", "releaseStage", "releaseType", "frequency", "goal", "source"]; if (intent === "beats") return ["intent", "beatMood", "beatGenre", "beatBudget", "goal", "source"]; if (intent === "producer") return ["intent", "producerStage", "producerNeeds", "goal", "source"]; if (intent === "promotion") return ["intent", "promotionGoal", "releaseTiming", "goal", "source"]; return ["intent", "exploreTopic", "goal", "source"]; }
function opts(values: string[]): Option[] { return values.map(value => ({ value: value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), title: value })); }

function getScreen(step: Step, c: OnboardingContext, answer: (field: keyof OnboardingContext, value: string, next: Step) => void, go: (next: Step, update?: OnboardingContext) => void, finish: (update?: OnboardingContext) => void): { question: string; options: Option[]; selected?: string; onSelect: (v: string) => void; note?: string; steps?: string[]; action?: { label: string; onClick: () => void } } {
  const goalNext = (field: keyof OnboardingContext, value: string) => answer(field, value, "goal");
  if (step === "intent") return { question: "What are you trying to make happen?", options: intents, selected: c.primaryIntent, onSelect: v => answer("primaryIntent", v, v === "release" ? "releaseStage" : v === "beats" ? "beatMood" : v === "producer" ? "producerStage" : v === "promotion" ? "promotionGoal" : "exploreTopic") };
  if (step === "releaseStage") return { question: "Where is your release right now?", options: opts(["Ready to upload", "Still finishing it", "Already released before", "I’m new to distribution"]), selected: c.releaseStage, onSelect: v => answer("releaseStage", v, v === "ready-to-upload" ? "releaseType" : v === "still-finishing-it" ? "missing" : v === "already-released-before" ? "previous" : "beginner") };
  if (step === "releaseType") return { question: "What are you releasing?", options: opts(["Single", "EP", "Album", "Not sure yet"]), selected: c.releaseType, onSelect: v => answer("releaseType", v, "frequency") };
  if (step === "frequency") return { question: "How often do you plan to release?", options: opts(["Just this once", "A few releases this year", "Every month", "I’m building a serious catalogue", "Not sure yet"]), selected: c.releaseFrequency, onSelect: v => goalNext("releaseFrequency", v) };
  if (step === "missing") return { question: "What are you missing?", options: opts(["A beat", "Mix/master", "Artwork", "Artist profiles", "Release strategy", "I’m not sure"]), selected: c.missingRequirement, onSelect: v => goalNext("missingRequirement", v) };
  if (step === "previous") return { question: "Moving an existing release to HYMN?", options: opts(["Yes", "No, I’m releasing something new"]), selected: c.previouslyReleased ? "yes" : undefined, onSelect: v => { go("goal", { previouslyReleased: v === "yes" }); } , note: "Moving a release may require its existing UPC and ISRC. We’ll surface that in the release flow." };
  if (step === "beginner") return { question: "Distribution, without the mystery.", options: [], onSelect: () => {}, steps: ["You upload your music", "HYMN reviews the release", "It moves into distribution", "You track every step from your dashboard"], note: "You don’t need to understand everything today. We’ll guide you through it.", action: { label: "Continue", onClick: () => go("goal") } };
  if (step === "beatMood") return { question: "What are you trying to sound like?", options: opts(["Dark and aggressive", "Melodic and emotional", "Energetic", "Smooth and laid-back", "Experimental", "Surprise me"]), selected: c.beatMood, onSelect: v => answer("beatMood", v, "beatGenre") };
  if (step === "beatGenre") return { question: "What are you making?", options: opts(["Rap", "DHH", "Pop", "R&B", "Indie", "Something else"]), selected: c.beatGenre, onSelect: v => answer("beatGenre", v, "beatBudget") };
  if (step === "beatBudget") return { question: "What is your budget?", options: [{ value: "under-500", title: "Under ₹500" }, { value: "500-1500", title: "₹500–₹1,500" }, { value: "1500-plus", title: "₹1,500+" }, { value: "all", title: "Show everything" }], selected: c.beatBudget, onSelect: v => goalNext("beatBudget", v) };
  if (step === "producerStage") return { question: "Where are you as a producer?", options: opts(["I already sell beats", "I have beats but no store", "I’m just starting", "I produce privately for artists"]), selected: c.producerStage, onSelect: v => answer("producerStage", v, "producerNeeds") };
  if (step === "producerNeeds") return { question: "What do you want HYMN to help with?", options: opts(["Storefront", "Licensing", "Payments", "Exposure", "All of it"]), selected: c.producerNeeds, onSelect: v => goalNext("producerNeeds", v) };
  if (step === "promotionGoal") return { question: "What matters most right now?", options: opts(["More listeners", "Better playlist positioning", "Social media content", "Release strategy", "Understanding my numbers"]), selected: c.promotionGoal, onSelect: v => answer("promotionGoal", v, "releaseTiming") };
  if (step === "releaseTiming") return { question: "Has the song already been released?", options: opts(["Yes", "No, it is upcoming"]), selected: c.releaseTiming, onSelect: v => goalNext("releaseTiming", v) };
  if (step === "exploreTopic") return { question: "What do you want to understand?", options: opts(["How distribution works", "How artists earn", "How beat licensing works", "What HYMN actually does", "Browse everything"]), selected: c.explorationTopic, onSelect: v => goalNext("explorationTopic", v) };
  if (step === "goal") return { question: "What would make this year successful?", options: opts(goals), selected: c.personalGoal, onSelect: v => answer("personalGoal", v, "source") };
  return { question: "Where did you discover HYMN?", options: [...opts(sources), { value: "skip", title: "Prefer not to say" }], selected: c.discoverySource, onSelect: v => finish(v === "skip" ? {} : { discoverySource: v }) };
}

function Result({ context: c, navigate }: { context: OnboardingContext; navigate: (href: string, login?: { title: string; body: string; secondary: string }) => void }) {
  let title = "Your HYMN starting point"; let route = "Explore HYMN"; let href: string = ONBOARDING_ROUTES.learn; let primary = "Enter HYMN"; let login: { title: string; body: string; secondary: string } | undefined;
  let insight = "No pressure. Your workspace will be ready whenever you are.";
  if (c.primaryIntent === "beats" || c.missingRequirement === "a-beat") { title = `Your beat shelf is ready, ${c.name}.`; route = [c.beatMood, c.beatGenre, c.beatBudget].filter(Boolean).join(" · "); href = beatStoreHref(c); primary = "Explore my beats"; login = { title: "Log in to use the Beat Store", body: "Sign in to save beats, purchase licences, access downloads, and track orders.", secondary: "Browse first" }; }
  else if (c.primaryIntent === "producer") { title = "Your producer path is ready"; route = c.producerNeeds || "Producer access"; href = ONBOARDING_ROUTES.producerAccess; primary = "Apply for producer access"; insight = "You keep 70% of each verified beat sale. HYMN retains 30%. Producer access remains admin-approved."; login = { title: "Log in for producer access", body: "Sign in to request producer access. Producer roles remain admin-approved.", secondary: "Not now" }; }
  else if (c.primaryIntent === "promotion") { title = "Your growth route is ready"; route = c.promotionGoal || "Release support"; href = ONBOARDING_ROUTES.services; primary = "See the next step"; }
  else if (c.primaryIntent === "release") { const frequent = ["a-few-releases-this-year", "every-month", "im-building-a-serious-catalogue"].includes(c.releaseFrequency || ""); const needsHelp = c.releaseStage === "still-finishing-it" && c.missingRequirement !== "a-beat"; if (needsHelp) { route = "Release preparation help"; href = ONBOARDING_ROUTES.services; primary = "Open release help"; } else if (frequent) { route = c.releaseFrequency === "a-few-releases-this-year" ? "Half-Yearly" : c.releaseFrequency === "every-month" ? "Yearly" : "Yearly+"; href = `${ONBOARDING_ROUTES.plans}?recommended=${route.toLowerCase().replace("+", "_plus")}`; primary = "View recommended plans"; } else { route = c.previouslyReleased ? "Release transfer preparation" : "One-Time Review"; href = ONBOARDING_ROUTES.singleRelease; primary = "Start my release"; login = { title: "You’ll need to log in before distribution", body: "Create or access your HYMN account to save your release, upload files, submit metadata, and track its status.", secondary: "Not now" }; } }
  return <div className="mx-auto w-full max-w-3xl"><p className="text-left text-xs font-bold uppercase tracking-[.22em] text-[var(--onboarding-accent)]">Path ready</p><h1 className="mt-4 text-left text-3xl font-semibold tracking-[-.04em] sm:text-5xl"><TypingText text={title} /></h1><div className="mt-10 border-y border-[var(--border)] py-7 sm:py-9"><dl className="grid gap-x-10 sm:grid-cols-2"><Summary label="Goal" value={c.personalGoal || c.primaryIntent} /><Summary label="Current stage" value={c.releaseStage || c.producerStage || c.releaseTiming || "Ready to explore"} /><Summary label="Recommended route" value={route} /><Summary label="Next step" value={primary} /></dl><div className="mt-8"><Primary onClick={() => navigate(href, login)}>{primary}</Primary></div>{c.primaryIntent === "release" && href.startsWith("/distribution?recommended") ? <button onClick={() => navigate(ONBOARDING_ROUTES.singleRelease, { title: "You’ll need to log in before distribution", body: "Sign in to save and submit your release. Your onboarding choices will stay here.", secondary: "Not now" })} className="mt-4 min-h-11 text-sm font-semibold text-[var(--text-muted)]">Try one release first</button> : null}</div></div>;
}
function Summary({ label, value }: { label: string; value?: string }) { return <div className="border-b border-[var(--border)] py-5 first:pt-0"><dt className="text-[10px] font-bold uppercase tracking-[.18em] text-[var(--text-soft)]">{label}</dt><dd className="mt-2 text-base font-semibold capitalize tracking-[-.01em]">{value?.replace(/-/g, " ") || "—"}</dd></div>; }

// vercel trigger 12
