"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Check, ShieldCheck, Upload, WalletCards } from "lucide-react";

export function ProducerEnrollment({ name }: { name: string }) {
  const [producerName, setProducerName] = useState(name), [genre, setGenre] = useState(""), [rightsConfirmed, setRightsConfirmed] = useState(false), [ageConfirmed, setAgeConfirmed] = useState(false), [termsAccepted, setTermsAccepted] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function enroll(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    const response = await fetch("/api/producer/enroll", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ producerName, genre, rightsConfirmed, ageConfirmed, termsAccepted }) });
    const data = await response.json();
    if (!response.ok) { setError(data.error || "Could not activate producer access."); setBusy(false); return; }
    window.location.assign(data.href);
  }
  return <main className="shell py-8 sm:py-14"><section className="mx-auto grid max-w-5xl overflow-hidden rounded-[2rem] border border-[var(--border)] bg-[var(--card)] shadow-[0_24px_80px_rgba(0,0,0,.14)] lg:grid-cols-[.9fr_1.1fr]">
    <div className="bg-[var(--text)] p-7 text-[var(--bg)] sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.2em] opacity-60">HYMN Producer</p><h1 className="mt-5 text-4xl font-semibold tracking-[-.05em]">Open your beat store today.</h1><p className="mt-4 max-w-md text-sm leading-6 opacity-70">Anyone can join. Upload original work, choose your licence prices, and submit each beat for marketplace review.</p><div className="mt-8 grid gap-4 text-sm"><div className="flex gap-3"><Upload className="h-5 w-5 shrink-0" /><span>Upload previews, artwork and licensed deliverables</span></div><div className="flex gap-3"><WalletCards className="h-5 w-5 shrink-0" /><span>Set tier pricing and track verified sales</span></div><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0" /><span>Every listing is reviewed for rights, quality and accuracy</span></div></div><p className="mt-8 text-xs leading-5 opacity-55">HYMN records a 30% marketplace share on eligible sales. Your producer share is 70%, subject to verified payment, refunds, disputes and payout checks.</p></div>
    <form onSubmit={enroll} className="p-7 sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[var(--accent)]">Self-service enrollment</p><h2 className="mt-3 text-2xl font-semibold">Create your producer workspace</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Producer name<input className="field mt-2 w-full" value={producerName} onChange={e => setProducerName(e.target.value)} required minLength={2} /></label><label className="text-sm font-semibold">Primary sound<input className="field mt-2 w-full" value={genre} onChange={e => setGenre(e.target.value)} required minLength={2} placeholder="Trap, R&B, Drill…" /></label></div>
      <div className="mt-6 grid gap-3"><label className="flex items-start gap-3 rounded-xl border border-[var(--border)] p-3 text-sm"><input className="mt-1" type="checkbox" checked={rightsConfirmed} onChange={e => setRightsConfirmed(e.target.checked)} required /><span>I own or control every beat, sample, loop, artwork and deliverable I upload, and can grant the licences I offer.</span></label><label className="flex items-start gap-3 rounded-xl border border-[var(--border)] p-3 text-sm"><input className="mt-1" type="checkbox" checked={ageConfirmed} onChange={e => setAgeConfirmed(e.target.checked)} required /><span>I am at least 18 years old and can enter a binding marketplace agreement.</span></label><label className="flex items-start gap-3 rounded-xl border border-[var(--border)] p-3 text-sm"><input className="mt-1" type="checkbox" checked={termsAccepted} onChange={e => setTermsAccepted(e.target.checked)} required /><span>I accept the <Link className="font-semibold underline" href="/policies/producer-terms" target="_blank">Producer Terms</Link>, <Link className="font-semibold underline" href="/policies/beat-store-terms" target="_blank">Beat Store Terms</Link> and copyright rules.</span></label></div>
      <div className="mt-5 rounded-xl bg-[var(--bg-soft)] p-4 text-xs leading-5 text-[var(--text-muted)]"><strong className="text-[var(--text)]">Before a beat goes live:</strong> HYMN checks preview playback, metadata, artwork, prices, deliverables and rights signals. We may request evidence, corrections or remove disputed listings.</div>{error ? <p className="mt-4 text-sm text-[var(--danger)]" role="alert">{error}</p> : null}<button className="btn-primary mt-6 w-full justify-center" disabled={busy}>{busy ? "Opening workspace…" : "Become a producer"}<ArrowRight className="ml-2 h-4 w-4" /></button><p className="mt-4 flex items-center justify-center gap-2 text-xs text-[var(--text-soft)]"><Check className="h-3.5 w-3.5" />No manual appointment or portfolio approval required.</p>
    </form></section></main>;
}
