"use client";

import { useEffect, useRef, useState } from "react";
import { AlertCircle, CheckCircle2, Download, FileSpreadsheet, History, Search, UploadCloud, X } from "lucide-react";
import { ContextualHelp } from "@/components/contextual-help";

type ImportRow = { id: number; originalFileName: string; reportingMonth?: string | null; createdAt: string; status: string; importedBy: { name: string; email: string }; jobs: Array<{ rowCount: number; matchedCount: number; unmatchedCount: number; errorCount: number; totalRevenue: string; progress: number; phase: string }> };
const phases = ["Uploading", "Validating", "Reading report", "Matching releases", "Applying splits", "Updating dashboards", "Generating ledgers", "Completed"];

async function readApiResponse(response: Response) { const text = await response.text(); if (!text) return {}; try { return JSON.parse(text) as Record<string, any>; } catch { return { error: response.ok ? "The server returned an invalid response." : `Server error (${response.status}). Check the terminal for details.` }; } }
const fileSize = (size: number) => size < 1024 * 1024 ? `${Math.ceil(size / 1024)} KB` : `${(size / 1024 / 1024).toFixed(1)} MB`;

export function RoyaltyManagement() {
  const inputRef = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [dragging, setDragging] = useState(false); const [imports, setImports] = useState<ImportRow[]>([]); const [preview, setPreview] = useState<any>(null); const [message, setMessage] = useState(""); const [isError, setIsError] = useState(false); const [busy, setBusy] = useState(false); const [phase, setPhase] = useState(0);
  async function load() { const response = await fetch("/api/admin/royalties/history"); const data = await readApiResponse(response); if (response.ok && Array.isArray(data.imports)) setImports(data.imports); else if (!response.ok) { setMessage(data.error || "Could not load import history."); setIsError(true); } }
  useEffect(() => { void load(); }, []);
  function choose(next: File | null) { if (!next) return; const extension = next.name.split(".").pop()?.toLowerCase(); if (!extension || !["csv", "xlsx"].includes(extension)) { setMessage("Choose a distributor CSV or XLSX report."); setIsError(true); return; } setFile(next); setPreview(null); setMessage(""); setIsError(false); }
  async function upload(confirm = false, force = false) { if (!file) return; setBusy(true); setMessage(""); setIsError(false); setPhase(confirm ? 4 : 1); const form = new FormData(); form.set("file", file); form.set("confirm", String(confirm)); form.set("force", String(force)); const timer = window.setInterval(() => setPhase(current => Math.min(confirm ? 6 : 3, current + 1)), 700); try { const response = await fetch("/api/admin/royalties/import", { method: "POST", body: form }); const data = await readApiResponse(response); if (!response.ok) { if (response.status === 409 && data.canForce) { setPreview({ duplicate: data.duplicate }); setMessage(data.error); } else setMessage(data.missingColumns ? `${data.error} Missing: ${data.missingColumns.join(", ")}` : data.error || "Import failed."); setIsError(true); return; } if (!confirm) { setPreview(data); setMessage(`${data.matched} rows matched. Review the summary before creating ledger entries.`); } else { setPhase(7); setPreview(null); setMessage("Revenue report imported successfully."); await load(); } } catch (error) { setMessage(error instanceof Error ? error.message : "Could not reach the import service."); setIsError(true); } finally { window.clearInterval(timer); setBusy(false); } }
  async function rollback(id: number) { const reason = window.prompt("Reason for rolling back this import?"); if (!reason) return; const response = await fetch(`/api/admin/royalties/imports/${id}/rollback`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason }) }); const data = await readApiResponse(response); setMessage(response.ok ? `Import rolled back (${data.reversedLines} ledger rows reversed).` : data.error || "Rollback failed."); setIsError(!response.ok); if (response.ok) await load(); }

  return <div className="grid gap-8">
    <section className="overflow-hidden rounded-[28px] border shadow-sm" style={{ borderColor: "var(--border)", background: "var(--card)" }}>
      <div className="border-b px-6 py-6 sm:px-8" style={{ borderColor: "var(--border)" }}><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl" style={{ background: "var(--bg-soft)" }}><UploadCloud size={23} /></span><div><h2 className="text-xl font-semibold sm:text-2xl">Upload revenue report <ContextualHelp faqId="royalty-imports" label="Royalty imports">Distributor reports are validated, matched, and previewed before HYMN creates Royalty Ledger entries.</ContextualHelp></h2><p className="mt-2 max-w-3xl text-sm leading-6" style={{ color: "var(--text-muted)" }}>Upload the monthly distributor statement as CSV or Excel. HYMN validates every row and shows a preview before creating financial records.</p></div></div></div>
      <div className="p-6 sm:p-8"><input ref={inputRef} className="sr-only" type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event => choose(event.target.files?.[0] ?? null)} />
        {!file ? <button type="button" onClick={() => inputRef.current?.click()} onDragEnter={event => { event.preventDefault(); setDragging(true); }} onDragOver={event => event.preventDefault()} onDragLeave={() => setDragging(false)} onDrop={event => { event.preventDefault(); setDragging(false); choose(event.dataTransfer.files?.[0] ?? null); }} className="flex min-h-56 w-full flex-col items-center justify-center rounded-3xl border-2 border-dashed p-8 text-center transition" style={{ borderColor: dragging ? "var(--text)" : "var(--border)", background: dragging ? "var(--bg-soft)" : "transparent" }}><span className="grid h-16 w-16 place-items-center rounded-full" style={{ background: "var(--bg-soft)" }}><FileSpreadsheet size={29} /></span><strong className="mt-5 text-lg">Drop your report here</strong><span className="mt-2 text-sm" style={{ color: "var(--text-muted)" }}>or click to browse · CSV and XLSX · maximum 50 MB</span></button> : <div className="flex flex-col gap-5 rounded-3xl border p-5 sm:flex-row sm:items-center sm:justify-between" style={{ borderColor: "var(--border)", background: "var(--bg-soft)" }}><div className="flex min-w-0 items-center gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl" style={{ background: "var(--card)" }}><FileSpreadsheet size={26} /></span><div className="min-w-0"><p className="truncate font-semibold">{file.name}</p><p className="mt-1 text-sm uppercase tracking-wide" style={{ color: "var(--text-muted)" }}>{file.name.split(".").pop()} · {fileSize(file.size)}</p></div></div><button type="button" className="btn-outline inline-flex items-center justify-center gap-2" disabled={busy} onClick={() => { setFile(null); setPreview(null); setMessage(""); if (inputRef.current) inputRef.current.value = ""; }}><X size={16} /> Remove</button></div>}
        {busy ? <div className="mt-6 rounded-2xl border p-5" style={{ borderColor: "var(--border)" }}><div className="flex items-center justify-between gap-3 text-sm"><strong>{phases[phase]}…</strong><span style={{ color: "var(--text-muted)" }}>{Math.round(((phase + 1) / phases.length) * 100)}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full" style={{ background: "var(--bg-soft)" }}><div className="h-full rounded-full transition-all duration-500" style={{ width: `${((phase + 1) / phases.length) * 100}%`, background: "var(--text)" }} /></div></div> : null}
        {message ? <div className="mt-6 flex items-start gap-3 rounded-2xl border p-4 text-sm" style={{ borderColor: isError ? "var(--danger)" : "var(--border)", background: isError ? "var(--danger-soft)" : "var(--bg-soft)" }}>{isError ? <AlertCircle className="shrink-0" size={19} /> : <CheckCircle2 className="shrink-0" size={19} />}<span className="leading-6">{message}</span></div> : null}
        {preview && !preview.duplicate ? <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Report rows", preview.rows], ["Matched", preview.matched], ["Manual review", preview.unmatched], ["Failed", preview.failed], ["Net revenue", preview.totalRevenue]].map(([label, amount]) => <div className="rounded-2xl border p-4" style={{ borderColor: "var(--border)" }} key={String(label)}><span className="text-xs font-semibold uppercase tracking-wider" style={{ color: "var(--text-muted)" }}>{label}</span><strong className="mt-2 block text-xl">{String(amount)}</strong></div>)}</div> : null}
        <div className="mt-6 flex flex-wrap gap-3"><button className="btn-primary inline-flex items-center gap-2" disabled={!file || busy} onClick={() => upload(false)}><Search size={16} /> Validate & preview</button>{preview && !preview.duplicate ? <button className="btn-primary inline-flex items-center gap-2" disabled={busy} onClick={() => upload(true)}><CheckCircle2 size={16} /> Confirm import</button> : null}{preview?.duplicate ? <><button className="btn-outline" onClick={() => { setPreview(null); setFile(null); }}>Cancel</button><button className="btn-primary" disabled={busy} onClick={() => upload(true, true)}>Force import</button></> : null}<a className="btn-outline inline-flex items-center gap-2" href="/api/admin/royalties/export"><Download size={16} /> Export reports</a><a className="btn-outline inline-flex items-center gap-2" href="/admin/royalties/reconciliation"><Search size={16} /> Manual review</a></div>
      </div>
    </section>
    <section className="overflow-hidden rounded-[28px] border shadow-sm" style={{ borderColor: "var(--border)", background: "var(--card)" }}><div className="flex items-center gap-4 border-b px-6 py-6 sm:px-8" style={{ borderColor: "var(--border)" }}><span className="grid h-11 w-11 place-items-center rounded-2xl" style={{ background: "var(--bg-soft)" }}><History size={21} /></span><div><h2 className="text-xl font-semibold">Import history</h2><p className="mt-1 text-sm" style={{ color: "var(--text-muted)" }}>Immutable monthly reports and processing results.</p></div></div><div className="overflow-x-auto">{imports.length ? <table className="w-full min-w-[900px] text-left text-sm"><thead style={{ background: "var(--bg-soft)" }}><tr>{["ID", "File", "Reporting month", "Imported by", "Rows", "Matched", "Review", "Status", "Actions"].map(item => <th className="px-6 py-4 text-xs uppercase tracking-wider" key={item}>{item}</th>)}</tr></thead><tbody>{imports.map(item => { const job = item.jobs[0]; return <tr className="border-t" style={{ borderColor: "var(--border)" }} key={item.id}><td className="px-6 py-4">#{item.id}</td><td className="max-w-52 truncate px-6 py-4 font-medium">{item.originalFileName}</td><td className="px-6 py-4">{item.reportingMonth ? new Date(item.reportingMonth).toLocaleDateString(undefined, { month: "short", year: "numeric" }) : "—"}</td><td className="px-6 py-4">{item.importedBy.name || item.importedBy.email}</td><td className="px-6 py-4">{job?.rowCount ?? 0}</td><td className="px-6 py-4">{job?.matchedCount ?? 0}</td><td className="px-6 py-4">{job?.unmatchedCount ?? 0}</td><td className="px-6 py-4"><span className="status-pill capitalize">{item.status.replaceAll("_", " ")}</span></td><td className="px-6 py-4">{item.status === "imported" ? <button className="btn-outline" onClick={() => rollback(item.id)}>Rollback</button> : "—"}</td></tr>; })}</tbody></table> : <div className="px-6 py-14 text-center sm:px-8"><History className="mx-auto" size={30} /><h3 className="mt-4 font-semibold">No imports yet</h3><p className="mt-2 text-sm" style={{ color: "var(--text-muted)" }}>Validated reports will appear here after the first successful import.</p></div>}</div></section>
  </div>;
}

// vercel trigger 14
