"use client";
import { useState } from "react";

type Row = { id: number; sourceLineNumber?: number | null; isrc?: string | null; upc?: string | null; rawData: Record<string, unknown>; statement?: { provider: string; currency: string } | null };
type ReleaseOption = { id: number; title: string; artistName: string; upc?: string | null; tracks: Array<{ id: number; title: string; isrc?: string | null }> };
export function RoyaltyReconciliationQueue({ initialRows, releases }: { initialRows: Row[]; releases: ReleaseOption[] }) {
  const [rows, setRows] = useState(initialRows); const [drafts, setDrafts] = useState<Record<number, { releaseId: string; trackId: string; note: string }>>({}); const [messages, setMessages] = useState<Record<number, string>>({});
  const draft = (id: number) => drafts[id] ?? { releaseId: "", trackId: "", note: "" };
  const patch = (id: number, value: Partial<ReturnType<typeof draft>>) => setDrafts(current => ({ ...current, [id]: { ...draft(id), ...value } }));
  async function resolve(id: number) { const value = draft(id); setMessages(current => ({ ...current, [id]: "Saving…" })); const response = await fetch(`/api/admin/royalties/unmatched/${id}/resolve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ releaseId: Number(value.releaseId), trackId: value.trackId ? Number(value.trackId) : null, note: value.note }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setMessages(current => ({ ...current, [id]: data.error || "Resolution failed." })); return; } setRows(current => current.filter(row => row.id !== id)); }
  return <div className="mt-6 grid gap-4">{rows.map(row => { const selected = releases.find(release => String(release.id) === draft(row.id).releaseId); return <article key={row.id} className="surface-card"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase tracking-wider" style={{ color: "var(--text-soft)" }}>{row.statement?.provider ?? "Statement"} · line {row.sourceLineNumber ?? "?"}</p><p className="mt-2 font-semibold">ISRC {row.isrc || "—"} · UPC {row.upc || "—"}</p></div><span className="status-pill">Unmatched</span></div><pre className="mt-4 max-h-40 overflow-auto rounded-xl border p-3 text-xs" style={{ borderColor: "var(--border)", background: "var(--bg-soft)" }}>{JSON.stringify(row.rawData, null, 2)}</pre><div className="mt-4 grid gap-3 md:grid-cols-3"><select className="input" value={draft(row.id).releaseId} onChange={event => patch(row.id, { releaseId: event.target.value, trackId: "" })}><option value="">Select verified release</option>{releases.map(release => <option key={release.id} value={release.id}>{release.title} — {release.artistName} ({release.upc || "no UPC"})</option>)}</select><select className="input" value={draft(row.id).trackId} onChange={event => patch(row.id, { trackId: event.target.value })}><option value="">Release-level match</option>{selected?.tracks.map(track => <option key={track.id} value={track.id}>{track.title} ({track.isrc || "no ISRC"})</option>)}</select><input className="input" value={draft(row.id).note} onChange={event => patch(row.id, { note: event.target.value })} placeholder="Required matching evidence" /></div><div className="mt-3 flex items-center gap-3"><button type="button" className="btn-primary pressable" onClick={() => resolve(row.id)}>Resolve row</button><span className="text-sm" aria-live="polite" style={{ color: "var(--text-muted)" }}>{messages[row.id]}</span></div></article>; })}{!rows.length ? <p className="surface-card text-sm" style={{ color: "var(--text-muted)" }}>No unmatched royalty rows.</p> : null}</div>;
}
// vercel trigger 9
