"use client";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Bell, Check, Disc3, IndianRupee, LifeBuoy, Music2, Plus, Store, Upload } from "lucide-react";
import { ContextualHelp } from "@/components/contextual-help";
import { getReleaseStatusPresentation } from "@/lib/release-status-presentation";
import type { Beat, Notification, Order, Release, SupportTicket, User } from "@/lib/types";

const money = (value: number) => `₹${Math.round(value || 0).toLocaleString("en-IN")}`;
const title = (release: Release) => release.releaseTitle?.trim() || release.trackName || "Untitled release";
const first = (name: string) => name.trim().split(/\s+/)[0] || "Artist";

export function CustomerHome({ user, releases, attention, earnings, notifications, tickets, onEarnings }: { user: User; releases: Release[]; attention: Array<{ title: string; detail: string; cta: string; href?: string }>; earnings?: { totalEarnings: number; availableBalance: number; pendingBalance: number } | null; notifications: Notification[]; tickets: SupportTicket[]; onEarnings: () => void }) {
  const recent = releases.slice(0, 4); const current = releases.find(item => ["changes_requested", "rejected", "failed", "under_review", "in_queue", "scheduled"].includes(item.status)) || releases[0]; const state = current ? getReleaseStatusPresentation(current.status) : null;
  if (!releases.length) return <div className="creator-home"><section className="creator-welcome creator-first-run"><div><p className="eyebrow">Your music starts here</p><h1>Welcome to HYMN, {first(user.name)}.</h1><p>Let’s get your first release out. This is where you’ll submit music, follow its progress, and see reported earnings.</p><Link href="/distribution/start" className="btn-primary pressable"><Plus /> Distribute your first track</Link></div><div className="creator-how"><p>How it works</p>{["Upload your music", "HYMN reviews it", "We send it for distribution", "Track status and reported earnings here"].map((item,index)=><div key={item}><span>{index+1}</span>{item}</div>)}</div></section><p className="creator-secondary-link">Not ready to release? <Link href="/beat-store">Browse beats <ArrowRight /></Link></p><OverviewUpdates notifications={notifications} tickets={tickets} /></div>;
  return <div className="creator-home">
    <section className="creator-welcome"><div><p className="eyebrow">Artist workspace</p><h1>Welcome back, {first(user.name)}.</h1><p>{state ? `${title(current!)} is ${state.label.toLowerCase()}. ${state.description}` : "Everything looks good. Ready for your next release?"}</p></div><div className="creator-primary-actions"><Link href="/distribution/start" className="btn-primary pressable"><Plus /> New release</Link><Link href="/beat-store" className="creator-text-action">Browse beats</Link><button onClick={onEarnings} className="creator-text-action">View earnings</button></div></section>
    <section className="creator-attention" aria-label="What needs your attention">{attention.length ? <><h2>What needs your attention</h2>{attention.slice(0,2).map((item,index)=><article key={`${item.title}-${index}`}><div><strong>{item.title}</strong><p>{item.detail}</p></div>{item.href ? <Link href={item.href}>{item.cta}<ArrowRight /></Link> : <span>{item.cta}</span>}</article>)}</> : <p className="creator-caught-up"><Check /> You’re all caught up.</p>}</section>
    <div className="creator-home-grid"><section className="creator-section"><div className="creator-section-head"><div><p className="eyebrow">Your music</p><h2>Recent releases</h2></div><button className="creator-view-all">View all releases <ArrowRight /></button></div><div className="release-compact-list">{recent.map(release=>{const status=getReleaseStatusPresentation(release.status);return <article key={release.id}><div className="release-compact-art">{release.artworkUrl ? <Image src={release.artworkUrl} alt="" width={72} height={72} /> : <Music2 />}</div><div className="release-compact-copy"><strong>{title(release)}</strong><span>{release.artistName}</span><em data-tone={status.tone}>{status.label}</em></div><Link href={`/dashboard/releases/${release.id}`}>Manage <ArrowRight /></Link></article>})}</div></section>
      <aside className="creator-section earnings-quiet"><p className="eyebrow">Money</p><h2>Reported earnings <ContextualHelp faqId="royalty-reporting" label="Reported earnings">Royalties appear after HYMN processes revenue reports received from the distribution infrastructure.</ContextualHelp></h2><strong>{money(earnings?.totalEarnings || 0)}</strong><div><span>Available for payout</span><b>{money(earnings?.availableBalance || 0)}</b></div><button onClick={onEarnings}>View earnings <ArrowRight /></button></aside></div>
    <section className="creator-quick-actions"><h2>Quick actions</h2><div><Link href="/distribution/start"><Upload />New release</Link><Link href="/beat-store"><Store />Browse beats</Link><Link href="/dashboard?tab=collaborators"><Music2 />Invite split</Link><button onClick={onEarnings}><IndianRupee />Earnings</button></div></section>
    <OverviewUpdates notifications={notifications} tickets={tickets} />
  </div>;
}

function OverviewUpdates({ notifications, tickets, workspace = "customer" }: { notifications: Notification[]; tickets?: SupportTicket[]; workspace?: "customer" | "producer" }) {
  const activity = notifications.slice(0, 5);
  const activityHref = workspace === "producer" ? "/producer/dashboard?tab=messages" : "/dashboard?tab=messages";
  return <section className={`overview-updates ${tickets ? "has-support" : ""}`}><div className="creator-section"><div className="creator-section-head"><div><p className="eyebrow">Latest</p><h2>Recent activity</h2></div><Link href={activityHref} className="creator-view-all">View activity <ArrowRight /></Link></div><div className="overview-update-list">{activity.map(item=><Link key={item.id} href={item.href || activityHref}><span className="overview-update-icon"><Bell /></span><span><strong>{item.title}</strong><small>{item.body}</small></span><time>{new Date(item.createdAt).toLocaleDateString("en-IN", { day:"numeric", month:"short" })}</time></Link>)}{!activity.length && <p className="overview-update-empty"><Check /> No new account activity.</p>}</div></div>
    {tickets ? <div className="creator-section"><div className="creator-section-head"><div><p className="eyebrow">Support</p><h2>Ticket updates</h2></div><Link href="/dashboard?tab=support" className="creator-view-all">Open support <ArrowRight /></Link></div><div className="overview-update-list">{tickets.slice(0,4).map(ticket=><Link key={ticket.id} href="/dashboard?tab=support"><span className="overview-update-icon"><LifeBuoy /></span><span><strong>{ticket.subject}</strong><small>Ticket #{ticket.id} · {ticket.status.replaceAll("_", " ")}</small></span><em data-status={ticket.status}>{ticket.status === "resolved" || ticket.status === "closed" ? "Complete" : "Updated"}</em></Link>)}{!tickets.length && <div className="overview-update-empty overview-support-empty"><LifeBuoy /><span><strong>No open support requests</strong><small>If you need help, HYMN Support is available here.</small></span></div>}</div></div> : null}</section>;
}

export function ProducerHome({ user, beats, orders, finance, notifications, onTab }: { user: User; beats: Beat[]; orders: Order[]; finance: any; notifications: Notification[]; onTab: (tab: "upload"|"catalog"|"sales"|"earnings") => void }) {
  if (!beats.length) return <div className="creator-home"><section className="creator-welcome creator-first-run"><div><p className="eyebrow">Producer workspace</p><h1>Build your storefront, {first(user.name)}.</h1><p>Upload your first beat and start building a catalogue artists can discover and license.</p><button onClick={()=>onTab("upload")} className="btn-primary pressable"><Upload /> Upload first beat</button></div><div className="creator-how"><p>Your producer workspace</p>{["Upload and price beats", "Manage your storefront", "Track verified sales", "Follow earnings and payouts"].map((item,index)=><div key={item}><span>{index+1}</span>{item}</div>)}</div></section><OverviewUpdates notifications={notifications} workspace="producer" /></div>;
  const sales = orders.flatMap(order=>order.items.map(item=>({ order,item }))).slice(0,4);
  return <div className="creator-home"><section className="creator-welcome"><div><p className="eyebrow">Producer workspace</p><h1>Welcome back, {first(user.name)}.</h1><p>Your catalogue, verified sales, and producer earnings—without the noise.</p></div><div className="creator-primary-actions"><button onClick={()=>onTab("upload")} className="btn-primary pressable"><Plus /> Upload beat</button><Link href="/beat-store" className="creator-text-action">View store</Link></div></section>
    <section className="creator-metrics"><div><span>Sales</span><strong>{finance.totalSales || 0}</strong></div><div><span>Gross revenue</span><strong>{money(finance.grossRevenue || finance.totalRevenue || 0)}</strong></div><div><span>Your share</span><strong>{money(finance.producerEarnings || 0)}</strong></div><div><span>Available payout</span><strong>{money(finance.availableBalance || 0)}</strong></div></section>
    <div className="creator-home-grid"><section className="creator-section"><div className="creator-section-head"><div><p className="eyebrow">Business</p><h2>Recent sales</h2></div><button onClick={()=>onTab("sales")} className="creator-view-all">View all <ArrowRight /></button></div><div className="producer-sale-list">{sales.map(({order,item},index)=><article key={`${order.id}-${index}`}><div><strong>{item.beatTitle || `Beat #${item.beatId}`}</strong><span>{order.buyerName ? `${order.buyerName.slice(0,1)}***` : "Artist"} · {item.licenseType}</span></div><b>{money(item.price*.7)}</b></article>)}</div></section><aside className="creator-section producer-share"><Disc3 /><h2>Every eligible beat sale</h2><div><span>Sale</span><b>100%</b></div><div><span>HYMN</span><b>30%</b></div><div className="is-emphasis"><span>You earn</span><b>70%</b></div><ContextualHelp faqId="producer-sales" label="Producer revenue share">Producers receive 70% of eligible beat-sale revenue. HYMN retains 30% under the marketplace revenue-share model.</ContextualHelp></aside></div>
    <section className="creator-section"><div className="creator-section-head"><div><p className="eyebrow">Catalogue</p><h2>Your beats</h2></div><button onClick={()=>onTab("catalog")} className="creator-view-all">Manage beats <ArrowRight /></button></div><div className="producer-beat-strip">{beats.slice(0,4).map(beat=><article key={beat.id}>{beat.artworkUrl ? <Image src={beat.artworkUrl} alt="" width={128} height={128}/> : <Disc3 />}<strong>{beat.title}</strong><span>{money(beat.price)} · {beat.enabled ? "Live" : "Not listed"}</span></article>)}</div></section>
    <OverviewUpdates notifications={notifications} workspace="producer" />
  </div>;
}
