"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import type { Release } from "@/lib/types";

type Data = { created: any[]; received: any[]; requests: any[]; earnings: any[] };
const tabs = ["overview", "requests", "join", "created", "shared", "earnings", "payout-details"] as const;
const roles = ["Primary Artist", "Featured Artist", "Producer", "Songwriter", "Composer", "Label", "Manager", "Other"];
const money = (value: unknown) => `₹${Number(value || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export function SplitsDashboard({ releases }: { releases: Release[] }) {
  const [tab, setTab] = useState<typeof tabs[number]>("overview");
  const [data, setData] = useState<Data>({ created: [], received: [], requests: [], earnings: [] });
  const [feedback, setFeedback] = useState(""); const [preview, setPreview] = useState<any>(null); const [credential, setCredential] = useState<any>(null);
  const load = useCallback(async () => { const [splits, payout] = await Promise.all([fetch("/api/splits", { cache: "no-store" }), fetch("/api/payout/credentials", { cache: "no-store" })]); if (splits.ok) setData(await splits.json()); if (payout.ok) setCredential((await payout.json()).credential); }, []);
  useEffect(() => { load(); const params = new URLSearchParams(window.location.search); const requested = params.get("tab"); if (requested && tabs.includes(requested as any)) setTab(requested as any); }, [load]);
  const respond = async (id: number, action: "accept" | "decline" | "revoke") => { const response = await fetch(`/api/splits/invites/${id}/${action}`, { method: "POST" }); const result = await response.json(); setFeedback(response.ok ? `Split invite ${action}ed.` : result.error); if (response.ok) { setPreview(null); await load(); } };
  async function createInvite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setFeedback(""); const form = event.currentTarget; const values = new FormData(form); let splitId = Number(values.get("splitRecordId")); if (!splitId) { const record = await fetch("/api/splits", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ releaseId: Number(values.get("releaseId")) }) }); const recordData = await record.json(); if (!record.ok) return setFeedback(recordData.error); splitId = recordData.split.id; }
    const response = await fetch("/api/splits/invites", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ splitRecordId: splitId, method: values.get("method"), recipientEmail: values.get("recipientEmail"), recipientName: values.get("recipientName"), role: values.get("role"), sharePercent: Number(values.get("sharePercent")), payoutEligible: true, note: values.get("note") }) }); const result = await response.json(); setFeedback(response.ok ? result.invite.splitCode ? `Split code: ${result.invite.splitCode} — expires in 10 hours.` : "Registered HYMN user invited." : result.error); if (response.ok) { form.reset(); await load(); }
  }
  async function join(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const code = String(new FormData(event.currentTarget).get("code") || ""); const response = await fetch("/api/splits/invites/join-code", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code }) }); const result = await response.json(); setPreview(response.ok ? result.preview : null); setFeedback(response.ok ? "Review the split before accepting." : result.error); }
  async function saveCredential(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/payout/credentials", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const result = await response.json(); setFeedback(response.ok ? "Payout details saved securely." : result.error); if (response.ok) setCredential(result.credential); }
  const totalEarned = data.earnings.filter((row) => row.status === "credited").reduce((sum, row) => sum + Number(row.netShareAmount), 0);
  const held = data.earnings.filter((row) => ["held", "pending_payout_details"].includes(row.status)).reduce((sum, row) => sum + Number(row.netShareAmount), 0);
  return <div className="space-y-5">
    <div className="flex flex-wrap gap-2">{tabs.map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={tab === item ? "btn-primary pressable px-3 py-2 text-xs capitalize" : "btn-outline pressable px-3 py-2 text-xs capitalize"}>{item.replace("payout-details", "Payout details")}</button>)}</div>
    {feedback ? <div className="rounded-xl border p-3 text-sm" style={{ borderColor: "var(--border-strong)", color: "var(--text)" }}>{feedback}</div> : null}
    {tab === "overview" ? <div className="grid gap-4 md:grid-cols-4"><Metric label="Pending requests" value={data.requests.length}/><Metric label="Splits created" value={data.created.length}/><Metric label="Credited earnings" value={money(totalEarned)}/><Metric label="Held earnings" value={money(held)}/></div> : null}
    {tab === "requests" ? <List empty="No pending split requests.">{data.requests.map((row) => <Card key={row.id} title={row.release.title} status="Pending"><p>From: {row.splitRecord.owner.name}</p><p>{row.role} · {Number(row.sharePercent)}% · {row.payoutEligible ? "Payout eligible" : "Credit only"}</p><div className="mt-3 flex gap-2"><button className="btn-primary px-3 py-2 text-xs" onClick={() => respond(row.id, "accept")}>Accept Split</button><button className="btn-outline px-3 py-2 text-xs" onClick={() => respond(row.id, "decline")}>Decline</button></div></Card>)}</List> : null}
    {tab === "join" ? <div className="grid gap-4 lg:grid-cols-2"><form onSubmit={join} className="surface-list-item grid gap-3 p-4"><h3 className="font-semibold">Join with a split code</h3><input name="code" required className="field uppercase" placeholder="HYMN-8F3K2Q"/><button className="btn-primary">Join Split</button></form>{preview ? <Card title={preview.releaseName} status="Code verified"><p>Owner: {preview.ownerName}</p><p>{preview.role} · {preview.sharePercent}%</p><p>Payout eligible: {preview.payoutEligible ? "Yes" : "No"}</p><div className="mt-3 flex gap-2"><button className="btn-primary px-3 py-2 text-xs" onClick={() => respond(preview.id, "accept")}>Accept Split</button><button className="btn-outline px-3 py-2 text-xs" onClick={() => respond(preview.id, "decline")}>Decline</button></div></Card> : null}</div> : null}
    {tab === "created" ? <div className="grid gap-5 lg:grid-cols-[0.8fr,1.2fr]"><form onSubmit={createInvite} className="surface-list-item grid gap-3 p-4"><h3 className="font-semibold">Add collaborator</h3><select name="releaseId" required className="field"><option value="">Select release</option>{releases.map((r) => <option key={r.id} value={r.id}>{r.releaseTitle || r.trackName}</option>)}</select><select name="splitRecordId" className="field"><option value="">Create/use release split</option>{data.created.map((r) => <option key={r.id} value={r.id}>{r.release.title} · {Number(r.totalSharePercent)}%</option>)}</select><select name="method" className="field"><option value="registered_email">Registered HYMN email</option><option value="split_code">10-hour split code</option></select><input name="recipientName" required className="field" placeholder="Recipient name"/><input name="recipientEmail" type="email" className="field" placeholder="Recipient HYMN email (email invite only)"/><select name="role" className="field">{roles.map((r) => <option key={r}>{r}</option>)}</select><input name="sharePercent" type="number" min="0.01" max="100" step="0.01" required className="field" placeholder="Share %"/><textarea name="note" className="field" placeholder="Optional note"/><button className="btn-primary">Create split invite</button></form><List empty="No splits created yet.">{data.created.map((record) => <Card key={record.id} title={record.release.title} status={`${Number(record.totalSharePercent)}% allocated`}><p className={Number(record.totalSharePercent) === 100 ? "text-emerald-300" : "text-amber-300"}>{Number(record.totalSharePercent) === 100 ? "Ready for distribution" : "Split total must equal 100% before earnings can be distributed."}</p>{record.recipients.map((row: any) => <div key={row.id} className="mt-3 border-t pt-3" style={{ borderColor: "var(--border)" }}><p>{row.recipientName} · {row.role} · {Number(row.sharePercent)}%</p><p className="text-xs capitalize">{row.inviteMethod.replace("_", " ")} · {row.inviteStatus}{row.splitCodeDisplay ? ` · ${row.splitCodeDisplay}` : ""}</p>{row.inviteStatus === "pending" ? <button className="btn-outline mt-2 px-3 py-1.5 text-xs" onClick={() => respond(row.id, "revoke")}>Revoke</button> : null}</div>)}</Card>)}</List></div> : null}
    {tab === "shared" ? <List empty="No accepted or declined shared splits.">{data.received.filter((r) => r.inviteStatus !== "pending").map((row) => <Card key={row.id} title={row.release.title} status={row.inviteStatus}><p>{row.role} · {Number(row.sharePercent)}% · Owner: {row.splitRecord.owner.name}</p></Card>)}</List> : null}
    {tab === "earnings" ? <List empty="No verified split earnings yet.">{data.earnings.map((row) => <Card key={row.id} title={row.release.title} status={row.status.replaceAll("_", " ")}><p>{row.track?.title || "Release level"} · {row.recipientRole} · {Number(row.sharePercent)}%</p><p className="mt-2 text-lg font-semibold">{money(row.netShareAmount)}</p><p className="text-xs">Statement: {new Date(row.royaltyLineItem.statementMonth).toLocaleDateString("en-IN", { month: "long", year: "numeric" })}</p></Card>)}</List> : null}
    {tab === "payout-details" ? <div className="grid gap-4 lg:grid-cols-2"><Card title="Current payout details" status={credential?.status || "missing"}><p>{credential?.method || "No method added"}</p><p>{credential?.upiIdMasked || credential?.bankAccountMasked || "Add payout details to receive your split earnings."}</p>{credential?.ifscMasked ? <p>IFSC: {credential.ifscMasked}</p> : null}</Card><form onSubmit={saveCredential} className="surface-list-item grid gap-3 p-4"><h3 className="font-semibold">Add or update payout details</h3><select name="method" className="field"><option value="UPI">UPI</option><option value="BANK">Bank Transfer</option></select><input name="upiId" className="field" placeholder="UPI ID"/><input name="accountHolderName" className="field" placeholder="Account holder name"/><input name="bankAccountNumber" className="field" placeholder="Bank account number"/><input name="ifsc" className="field uppercase" placeholder="IFSC"/><input name="taxInfo" className="field" placeholder="PAN / GST (optional)"/><button className="btn-primary">Save payout details</button></form></div> : null}
  </div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="metric-card"><p className="text-xs" style={{ color: "var(--text-soft)" }}>{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>; }
function List({ children, empty }: { children: React.ReactNode; empty: string }) { const count = Array.isArray(children) ? children.length : 1; return <div className="grid gap-3">{count ? children : <p className="text-sm" style={{ color: "var(--text-soft)" }}>{empty}</p>}</div>; }
function Card({ title, status, children }: { title: string; status: string; children: React.ReactNode }) { return <article className="surface-list-item p-4"><div className="flex items-start justify-between gap-3"><h3 className="font-semibold">{title}</h3><span className="status-pill status-pill-active capitalize">{status}</span></div><div className="mt-3 space-y-1 text-sm" style={{ color: "var(--text-muted)" }}>{children}</div></article>; }
