"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
type Props={listing:{publicId:string;title:string;engineer:string;standardPrice:number;beatPrice:number|null;turnaroundDays:number;includedRevisions:number};purchases:Array<{id:number;title:string;licenseType:string}>};
export function StudioStartForm({listing,purchases}:Props){
  const router=useRouter(),[title,setTitle]=useState(""),[beatPurchaseId,setBeatPurchaseId]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/studio/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({listingPublicId:listing.publicId,projectTitle:title,beatPurchaseId:beatPurchaseId?Number(beatPurchaseId):undefined,idempotencyKey:crypto.randomUUID(),termsAccepted:true})});const data=await response.json();if(!response.ok)throw new Error(data.error);router.push(`/studio/orders/${data.order.publicId}`)}catch(value){setError(value instanceof Error?value.message:"Could not start project.");setBusy(false)}}
  return <form onSubmit={submit} className="rounded-[2rem] border border-[var(--border)] bg-[var(--card)] p-6 sm:p-8"><p className="hymn-kicker">Project details</p><h1 className="mt-2 text-3xl font-semibold">Start with {listing.engineer}</h1><label className="mt-7 block text-sm font-medium">Track or project title<input className="input mt-2 w-full" value={title} onChange={event=>setTitle(event.target.value)} maxLength={160} required placeholder="Untitled record"/></label><label className="mt-5 block text-sm font-medium">Purchased beat <span className="text-[var(--text-soft)]">(optional)</span><select className="input mt-2 w-full" value={beatPurchaseId} onChange={event=>setBeatPurchaseId(event.target.value)}><option value="">I am bringing my own production</option>{purchases.map(item=><option key={item.id} value={item.id}>{item.title} · {item.licenseType}</option>)}</select></label><label className="mt-5 flex items-start gap-3 text-sm text-[var(--text-muted)]"><input className="mt-1" type="checkbox" required/><span>I agree to the <Link className="underline" href="/policies/studio-services-terms" target="_blank">Studio Services Terms</Link> and confirm I have authority to provide these source materials.</span></label>{error?<p className="mt-4 text-sm text-[var(--danger)]" role="alert">{error}</p>:null}<button className="btn-primary mt-7 w-full justify-center" disabled={busy}>{busy?"Creating secure order…":"Continue to payment"}</button><p className="mt-4 text-center text-xs text-[var(--text-soft)]">Your source files stay private and become available only to you, your engineer, and authorized HYMN operations staff.</p></form>
}
