"use client";
import { useState } from "react";
type Adjustment = { id: number; userId: number; amount: string; currency: string; reason: string; state: string; requestedBy: number; decisionNote?: string | null; subject: { name: string; email: string }; requester: { name: string }; approver?: { name: string } | null };
export function WalletAdjustmentQueue({ initialAdjustments, currentAdminId }: { initialAdjustments: Adjustment[]; currentAdminId: number }) {
  const [items, setItems] = useState(initialAdjustments); const [notes, setNotes] = useState<Record<number, string>>({}); const [messages, setMessages] = useState<Record<number, string>>({});
  async function decide(id: number, decision: "approved" | "rejected") { setMessages(value => ({ ...value, [id]: "Saving..." })); const response = await fetch(`/api/admin/wallet-adjustments/${id}/decision`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision, note: notes[id] || "" }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setMessages(value => ({ ...value, [id]: data.error || "Decision failed." })); return; } setItems(value => value.map(item => item.id === id ? { ...item, state: data.adjustment.state, decisionNote: data.adjustment.decisionNote } : item)); setMessages(value => ({ ...value, [id]: "Decision recorded." })); }
  return <div className="mt-6 grid gap-4">{items.map(item => <article className="surface-card" key={item.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{item.subject.name} · {item.currency} {item.amount}</h2><p className="text-sm" style={{ color: "var(--text-muted)" }}>{item.subject.email} · requested by {item.requester.name}</p></div><span className="status-pill capitalize">{item.state}</span></div><p className="mt-3">{item.reason}</p>{item.state === "pending" && <div className="mt-4 grid gap-3 md:grid-cols-[1fr,auto,auto]"><input className="input" value={notes[item.id] || ""} onChange={event => setNotes(value => ({ ...value, [item.id]: event.target.value }))} placeholder="Independent review evidence (required)" /><button className="btn-primary pressable" disabled={item.requestedBy === currentAdminId} onClick={() => decide(item.id, "approved")}>Approve</button><button className="btn-secondary pressable" disabled={item.requestedBy === currentAdminId} onClick={() => decide(item.id, "rejected")}>Reject</button></div>}<p className="mt-2 text-sm" aria-live="polite" style={{ color: "var(--text-muted)" }}>{item.requestedBy === currentAdminId && item.state === "pending" ? "A different administrator must decide this request." : messages[item.id]}</p></article>)}</div>;
}
// vercel trigger 9
