export type PolicySection = { title: string; paragraphs: string[]; items?: string[] };
export type PolicyDocument = { slug: string; title: string; summary: string; sections: PolicySection[] };

const responsibilities = "You are responsible for providing accurate information and holding every right, permission, licence, and authority needed for the content and instructions you submit.";
const review = "HYMN may validate, pause, reject, restrict, or escalate a submission where information is incomplete, rights are unclear, payment is unverified, fraud risk exists, or a partner requirement is not met.";

export const policyDocuments: PolicyDocument[] = [
  { slug: "privacy", title: "Privacy Policy", summary: "How HYMN handles account, release, payment, royalty, support, and operational data.", sections: [
    { title: "Data HYMN processes", paragraphs: ["HYMN processes account identity and role data, Google authentication identifiers where used, artist and producer profiles, release metadata, contributor records, private audio and artwork assets, Beat Store orders and licence records, payment references, payout verification details, support messages, notifications, security events, and administrative audit records."] },
    { title: "Why the data is used", paragraphs: ["Data is used to authenticate users, operate Customer and Producer Dashboards, review releases, submit accepted releases to DireNote, fulfil Beat Store purchases, import and reconcile revenue reports, maintain the Royalty Ledger, apply accepted revenue splits, process quarterly payouts, send transactional email, investigate fraud and rights complaints, and meet accounting or legal duties."] },
    { title: "Sharing, storage, and retention", paragraphs: ["HYMN shares only necessary data with service providers involved in authentication, hosting, private storage, payment processing, email delivery, distribution, and support. Release metadata and assets selected for distribution are sent to DireNote and relevant destinations. Records may be retained after account or release closure where required for ledgers, licences, disputes, fraud controls, audit trails, tax, or legal obligations."] },
    { title: "Your choices and requests", paragraphs: ["You may request access, correction, or deletion of eligible personal data through Contact Support. Some release, transaction, royalty, licence, payout, security, and audit records cannot be erased when retention is necessary to protect users, preserve financial history, or comply with law."] }
  ]},
  { slug: "terms", title: "Terms of Service", summary: "The agreement governing access to HYMN and its customer, producer, distribution, marketplace, and financial tools.", sections: [
    { title: "Agreement and account use", paragraphs: ["Using HYMN means you accept these terms and the policy that applies to each workflow you use. Accounts are role-based. You must provide accurate details, protect access to your email and session, and use only permissions assigned to you.", responsibilities] },
    { title: "Platform services", paragraphs: ["HYMN provides release preparation and review, DireNote distribution handoff, release-status tracking, artist profiles, producer profiles, Beat Store purchasing and licence fulfilment, royalty splits, imported revenue reflection, payout requests, notifications, and support workflows. Availability depends on configuration, eligibility, plan, payment, review, and third-party processing."] },
    { title: "Rights and licence to operate", paragraphs: ["You retain rights you own. You grant HYMN, DireNote, and selected service providers a non-exclusive licence limited to storing, validating, encoding, displaying, transmitting, distributing, monetizing, reporting, and administering submitted content and transactions."] },
    { title: "Referral rewards and HYMN credits", paragraphs: ["Referral rewards and HYMN release credits are promotional platform credits unless HYMN expressly states otherwise. They are not cash, music royalties, royalty earnings, or a withdrawable producer balance. A referral becomes eligible only after the referred new account completes a genuine, successful, positive-value qualifying purchase verified by HYMN.", "Self-referrals, circular referrals, duplicate or fraudulent accounts, test or administrative transactions, failed payments, and other abusive activity are not eligible. HYMN may reject, review, or reverse rewards following a refund, chargeback, payment reversal, or confirmed ineligibility, while preserving the original ledger history.", "HYMN may modify reward values or eligibility for future referrals. Valid credits already earned remain governed by the terms applicable to those credits, including checkout eligibility, expiry where expressly disclosed, and fraud or payment-reversal controls."] },
    { title: "Suspension and liability", paragraphs: [review, "HYMN does not promise store acceptance, a fixed live date, playlist placement, stream volume, revenue, or uninterrupted third-party availability. To the extent permitted by law, HYMN is not responsible for indirect losses caused by a store, payment provider, distributor, rights claimant, or information supplied by a user."] }
  ]},
  { slug: "distribution-terms", title: "Distribution Terms", summary: "Rules for release submission, HYMN review, DireNote delivery, store status, changes, and takedowns.", sections: [
    { title: "Submission authority", paragraphs: [responsibilities, "Each release must include final audio, authorized artwork, truthful metadata, complete contributor credits, ownership declarations, and existing UPC or ISRC values where the same catalog product or recording was previously released."] },
    { title: "HYMN and DireNote workflow", paragraphs: ["Payment or plan eligibility does not guarantee acceptance. HYMN performs metadata, artwork, audio, rights, and readiness checks. Accepted releases are validated and submitted to DireNote. DireNote and each destination control downstream processing and acceptance."] },
    { title: "Status, corrections, and delivery", paragraphs: ["Dashboard statuses reflect recorded workflow events and confirmations; they are not a promise that every destination has updated simultaneously. Corrections may be required before or after distributor submission. Store-side restrictions can make some post-delivery edits unavailable."] },
    { title: "Revenue share and removal", paragraphs: ["The release form discloses that DireNote retains 30% of Net Royalty Revenue and the remaining eligible 70% is reflected through HYMN, subject to matched reporting, splits, holds, adjustments, and payout rules. Takedowns require a tracked request and are not immediate."] }
  ]},
  { slug: "beat-store-terms", title: "Beat Store Terms", summary: "Rules for browsing, purchasing, delivering, and using beats and generated licence documents.", sections: [
    { title: "Marketplace role", paragraphs: ["HYMN records listings, verified purchases, licence tiers, private deliverables, and generated licence documents. The producer is responsible for the beat and the rights offered; the buyer is responsible for selecting a suitable licence and following its written scope."] },
    { title: "Payment and fulfilment", paragraphs: ["A purchase is complete only after payment verification. Authorized files and licence documents are provided through private account-bound download routes. Access can be held during fraud, chargeback, ownership, or fulfilment review."] },
    { title: "Licence controls", paragraphs: ["The licence document and selected tier—not a listing preview or marketing label—govern usage, exclusivity, credit, monetization, modification, and distribution rights. Purchasing a beat does not transfer underlying copyright unless the written licence expressly says so."] }
  ]},
  { slug: "producer-terms", title: "Producer Terms", summary: "Responsibilities for producer verification, profiles, beat listings, licences, sales, and payout records.", sections: [
    { title: "Verification and profile", paragraphs: ["Producer-only tools require an approved producer role or application. Profile names, biographies, images, links, tags, and locations must be accurate and must not impersonate another person or business."] },
    { title: "Listings and rights", paragraphs: ["A producer may list only beats they are authorized to license. Pricing, licence options, previews, deliverables, samples, and ownership claims must be accurate. HYMN may unpublish or hold a listing during rights, quality, fraud, or policy review."] },
    { title: "Sales and finance", paragraphs: ["Producer Dashboard sales and finance records depend on verified payments and recorded fulfilment. Refunds, disputes, fraud holds, administrative corrections, and applicable platform terms may change payable amounts."] }
  ]},
  { slug: "refund-policy", title: "Refund Policy", summary: "How HYMN reviews duplicate charges, failed payments, started services, subscriptions, and marketplace purchases.", sections: [
    { title: "Eligible review", paragraphs: ["HYMN reviews refund requests for duplicate verified charges, a debit without successful fulfilment, an incorrect amount collected by HYMN, or another circumstance required by applicable law. Submit the order and payment references from the paying account."] },
    { title: "Generally non-refundable work", paragraphs: ["Distribution review, metadata or asset checks, distributor submission, completed licence fulfilment, consumed subscription time, and other started or delivered services are generally non-refundable. A release or listing rejected for user-supplied rights, metadata, quality, or policy issues does not automatically qualify."] },
    { title: "Reversals and disputes", paragraphs: ["Bank and gateway reversals can take time outside HYMN’s control. Chargebacks or suspected payment abuse may pause associated releases, downloads, balances, or accounts while evidence is reviewed."] }
  ]},
  { slug: "cookie-policy", title: "Cookie Policy", summary: "How cookies and browser storage support authentication, security, preferences, and onboarding.", sections: [
    { title: "Essential storage", paragraphs: ["HYMN uses essential cookies or equivalent browser storage to maintain authenticated sessions, protect role-based routes, preserve security state, remember interface preferences, and support checkout or onboarding continuity."] },
    { title: "Operational measurement", paragraphs: ["Limited diagnostic or usage information may be processed to identify failures and improve workflows. HYMN does not describe essential session storage as optional advertising tracking."] },
    { title: "Controls", paragraphs: ["Browser controls can remove or block cookies, but doing so can sign you out, reset preferences, interrupt payment return flows, or prevent protected dashboards from operating correctly."] }
  ]},
  { slug: "copyright-policy", title: "Copyright Policy", summary: "Ownership standards for recordings, compositions, artwork, beats, samples, profiles, and monetization.", sections: [
    { title: "Rights standard", paragraphs: [responsibilities, "This includes master recordings, compositions, beats, samples, loops, voices, artwork, photographs, names, logos, and contributor approvals."] },
    { title: "Conflicting and restricted content", paragraphs: ["Do not submit unauthorized masters, misleading artist identities, non-exclusive material to exclusive fingerprinting systems, or content already controlled through a conflicting distributor or Content ID administrator."] },
    { title: "Evidence and action", paragraphs: [review, "HYMN may request licences, receipts, contracts, source files, identity evidence, or claimant correspondence. Decisions may include corrections, rejection, monetization restrictions, takedown processing, account limitations, or referral to DireNote or a destination."] }
  ]},
  { slug: "copyright-claims", title: "DMCA & Copyright Claim Procedure", summary: "How rights holders and users submit, answer, and resolve copyright complaints.", sections: [
    { title: "Submitting a claim", paragraphs: ["Send Contact Support the claimant’s identity and contact details, the protected work, the specific HYMN release, beat, profile, or asset, a clear explanation of the claimed infringement, supporting URLs or documents, and a good-faith declaration of authority."] },
    { title: "HYMN review", paragraphs: ["HYMN records the complaint, verifies that it is sufficiently specific, may restrict the disputed content, and may request information from the submitting user. HYMN can coordinate with DireNote, payment providers, or destinations where required."] },
    { title: "Response and misuse", paragraphs: ["A responding user must provide accurate ownership or licence evidence and may submit a lawful counter-position where applicable. False, abusive, or retaliatory complaints can lead to rejection, account action, or liability under applicable law."] }
  ]},
  { slug: "royalty-payout-policy", title: "Royalty & Payout Policy", summary: "How reported earnings enter the Royalty Ledger and become eligible for payout.", sections: [
    { title: "Reported revenue", paragraphs: ["HYMN reflects revenue only from imported distributor reports that pass validation and matching. Dashboard amounts are ledger records, not real-time estimates of streams that stores have not reported."] },
    { title: "Balances and requests", paragraphs: ["Matched net revenue and accepted splits determine user balances. Availability can be affected by reporting delays, thresholds, payout verification, active requests, holds, corrections, refunds, disputes, fraud review, or unmatched statement rows."] },
    { title: "Quarterly processing", paragraphs: ["HYMN can generate monthly and quarterly reports. Before a quarter is locked, unmatched rows are resolved or documented. Closing preserves totals, publishes eligible statements, records paid and held amounts, and carries forward unpaid available balances."] }
  ]},
  { slug: "revenue-split-policy", title: "Revenue Split Policy", summary: "How release owners invite recipients and how accepted percentages affect matched royalties.", sections: [
    { title: "Creating a split", paragraphs: ["A release owner sets explicit percentages and invites recipients through registered email or a time-limited join code. Contributor credits alone do not create financial entitlement."] },
    { title: "Acceptance and calculation", paragraphs: ["A recipient must accept the invitation before the split is treated as active. HYMN applies the recorded split configuration to eligible matched royalty line items and preserves the resulting split-earning records."] },
    { title: "Disputes and changes", paragraphs: ["Users must resolve ownership and percentage disputes between themselves and provide evidence when requested. HYMN may hold affected amounts during a dispute and does not retroactively invent or infer agreements."] }
  ]},
  { slug: "community-guidelines", title: "Community Guidelines", summary: "Standards for profiles, marketplace participation, support, and collaboration.", sections: [
    { title: "Professional participation", paragraphs: ["Use accurate identities, communicate respectfully, keep profiles and listings truthful, and honor licences, credits, split invitations, support requests, and commercial commitments."] },
    { title: "Prohibited conduct", paragraphs: ["Harassment, threats, hate, sexual exploitation, impersonation, spam, scams, deceptive listings, review manipulation, credential sharing, and retaliation against claimants or collaborators are not permitted."] },
    { title: "Enforcement", paragraphs: ["HYMN may remove public content, restrict messages or marketplace access, require verification, preserve evidence, suspend accounts, or refer serious matters to relevant providers or authorities."] }
  ]},
  { slug: "acceptable-use", title: "Acceptable Use Policy", summary: "Technical and operational rules for using HYMN systems.", sections: [
    { title: "Permitted use", paragraphs: ["Use HYMN only for legitimate account, distribution, marketplace, reporting, payout, support, and administrative activity within your assigned permissions."] },
    { title: "Technical abuse", paragraphs: ["Do not probe security, bypass access controls, scrape protected data, upload malware, automate abusive traffic, interfere with payments or webhooks, enumerate private assets, or attempt unauthorized administrative access."] },
    { title: "Commercial abuse", paragraphs: ["Do not manipulate streams, payments, referrals, refunds, licences, royalty reports, splits, verification, notifications, or fraud systems. HYMN may rate-limit, block, suspend, investigate, or preserve logs of suspected abuse."] }
  ]},
  { slug: "content-moderation", title: "Content Moderation Policy", summary: "How HYMN reviews public profiles, beat listings, release assets, and reported content.", sections: [
    { title: "Scope", paragraphs: ["Moderation covers artist and producer profiles, beat listings and previews, artwork, metadata, support submissions, and other user-provided content visible to users, administrators, partners, or destinations."] },
    { title: "Review signals", paragraphs: ["HYMN considers rights evidence, deceptive identity, explicit or harmful material, platform rules, fraud alerts, user reports, metadata consistency, audio and artwork quality, and applicable law."] },
    { title: "Outcomes", paragraphs: ["HYMN may request changes, limit visibility, reject a listing or release, restrict monetization, preserve evidence, suspend an account, or process partner and legal escalation. Decisions and reasons are recorded where the workflow supports them."] }
  ]},
  { slug: "artist-verification", title: "Artist Verification Policy", summary: "How artist identities and profile links are reviewed for catalog accuracy.", sections: [
    { title: "Identity and profiles", paragraphs: ["Artist names and linked profiles must identify the correct performer or project. Users should select an existing profile where available and avoid duplicate or misleading artist identities."] },
    { title: "Evidence", paragraphs: ["HYMN may request official profile links, catalog history, identity or authorization evidence, collaborator confirmation, or corrections before approving an artist association."] },
    { title: "Limits", paragraphs: ["Plan-specific artist-profile limits control how many profiles can be used. Verification supports accuracy but does not guarantee verification badges, editorial treatment, or profile merging by a destination."] }
  ]},
  { slug: "producer-verification", title: "Producer Verification Policy", summary: "How producer applications and marketplace access are reviewed.", sections: [
    { title: "Application review", paragraphs: ["Producer access depends on an application or role review. HYMN may assess identity, profile quality, portfolio information, rights posture, prior activity, and the completeness of submitted details."] },
    { title: "Approval and rejection", paragraphs: ["Approval enables Producer Dashboard workflows but does not endorse every future listing. Rejected or suspended applicants cannot use producer-only tools until access is approved or restored."] },
    { title: "Ongoing obligations", paragraphs: ["Producers must keep profiles, links, beat ownership, prices, licence terms, deliverables, and payout details accurate. Material changes can trigger renewed review."] }
  ]},
  { slug: "kyc-payout-verification", title: "KYC & Payout Verification", summary: "Identity and destination checks applied before payout processing.", sections: [
    { title: "Purpose", paragraphs: ["HYMN reviews payout identity and bank or UPI details to reduce fraud, payment errors, impersonation, sanctions risk, and misdirected funds."] },
    { title: "Review process", paragraphs: ["A payout profile can be pending, approved, rejected, or returned for correction. Authorized administrators see restricted or masked information and record review decisions. Additional evidence may be requested."] },
    { title: "Payout impact", paragraphs: ["Approval of a profile does not guarantee a payout request. Available balance, threshold, active-request controls, holds, quarter status, fraud review, and operational processing still apply."] }
  ]},
  { slug: "ai-content-disclosure", title: "AI Content Disclosure Policy", summary: "Disclosure and rights requirements for AI-assisted audio, voices, artwork, and metadata.", sections: [
    { title: "Disclosure", paragraphs: ["Answer AI-related release questions truthfully and provide supporting receipts or rights evidence where requested. Disclosure is part of rights and risk review; it is not automatic acceptance or rejection."] },
    { title: "Rights requirements", paragraphs: ["You must hold commercial rights to the generated output, prompts or source material where relevant, voices, likenesses, samples, lyrics, compositions, recordings, and artwork. Do not imitate or falsely attribute a real artist."] },
    { title: "Eligibility limits", paragraphs: ["AI-assisted content may be ineligible for Content ID, certain destinations, or monetization where rights are non-exclusive, output is insufficiently original, platform policy restricts it, or evidence is inadequate."] }
  ]},
  { slug: "metadata-guidelines", title: "Metadata Submission Guidelines", summary: "Standards for titles, artists, credits, identifiers, dates, language, genre, and ownership fields.", sections: [
    { title: "Accuracy", paragraphs: ["Enter titles, versions, artist roles, contributors, label, language, genre, mood, explicit status, territories, dates, ownership, and copyright information exactly as they should appear and as the rights evidence supports."] },
    { title: "Identifiers", paragraphs: ["Use an existing UPC and ISRC only when the release or unchanged recording was previously distributed under those identifiers. Do not copy identifiers from unrelated catalog products."] },
    { title: "Store readiness", paragraphs: ["Avoid promotional text, URLs, unsupported capitalization, role stuffing, duplicate profiles, misleading features, placeholder values, or metadata that conflicts with audio or artwork. HYMN may return fields for correction."] }
  ]},
  { slug: "release-review-policy", title: "Release Review Policy", summary: "What HYMN checks before a release can move to DireNote distribution.", sections: [
    { title: "Review Queue", paragraphs: ["HYMN checks metadata completeness, identifiers, contributor roles, artist-profile links, artwork compliance, audio readiness, ownership declarations, licences, AI disclosures, Content ID eligibility, payment, and distribution payload readiness."] },
    { title: "Decisions", paragraphs: ["A release may be approved, returned with field-level changes, rejected with a reason, or held for evidence. Resubmission returns the corrected release to the Review Queue; it does not erase previous decisions."] },
    { title: "Timing and partner review", paragraphs: ["Review time varies with complexity, evidence, queue volume, corrections, payment reconciliation, and partner requirements. HYMN approval allows DireNote submission but does not replace DireNote or destination review."] }
  ]},
  { slug: "takedown-policy", title: "Takedown Policy", summary: "How complete, store-specific, or territory-specific removal requests are handled.", sections: [
    { title: "Requesting removal", paragraphs: ["Use Manage Release to submit a tracked takedown request. Select complete, store-specific, or territory-specific scope; identify targets; provide a reason; and confirm authority and consequences."] },
    { title: "Processing", paragraphs: ["HYMN reviews the request and may seek evidence before forwarding it to DireNote or destinations. Submission is not immediate removal. Store caching, territory systems, and partner processing can delay disappearance."] },
    { title: "Records and revenue", paragraphs: ["Takedown does not delete historical release, audit, transaction, royalty, or request records. Revenue may continue to arrive for activity that occurred before removal and will be handled through the normal ledger and payout process."] }
  ]}
];

export function getPolicy(slug: string) { return policyDocuments.find((policy) => policy.slug === slug); }
